// India FDI Sector Data — based on DPIIT Consolidated FDI Policy (as amended).
// Always verify with the latest DPIIT press notes and RBI Master Directions.

export const FDI_SECTORS = [
  // ── Agriculture ──────────────────────────────────────────────────────────────
  {
    sector: "Agriculture & Animal Husbandry",
    subsectors: ["Floriculture", "Horticulture", "Apiculture", "Pisciculture", "Aquaculture", "Cultivation of vegetables & mushrooms", "Sericulture"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI permitted for specified agricultural activities. Excludes plantation crops (tea, coffee, rubber, cardamom, palm oil, olive oil) which are covered separately.",
    category: "Agriculture",
  },
  {
    sector: "Plantation (Tea, Coffee, Rubber, Cardamom, Palm Oil)",
    subsectors: ["Tea plantation", "Coffee plantation", "Rubber plantation", "Cardamom plantation", "Palm oil plantation"],
    limit: 100,
    route: "Government",
    conditions: "100% FDI with prior government approval. Disinvestment of 26% equity in favour of an Indian partner/Indian public within 5 years. Subject to state-level land ceiling laws.",
    category: "Agriculture",
  },
  {
    sector: "Mining (excluding Coal & Lignite)",
    subsectors: ["Gold mining", "Silver mining", "Copper mining", "Iron ore mining", "Zinc and lead mining", "Diamond mining"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route subject to Mines and Minerals (Development and Regulation) Act, MMDR Act requirements, and environmental clearances.",
    category: "Manufacturing",
  },
  {
    sector: "Coal & Lignite Mining",
    subsectors: ["Coal mining for captive use", "Coal washing", "Mining services"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI permitted for coal/lignite mining for captive consumption by power projects, iron & steel and cement units. Subject to Mines and Minerals Act.",
    category: "Manufacturing",
  },
  {
    sector: "Petroleum & Natural Gas",
    subsectors: ["Exploration activities", "Petroleum product pipelines", "Market study", "Investment in refineries"],
    limit: 100,
    route: "Automatic",
    conditions: "For private Indian companies: 100% automatic. PSU refineries: government approval for >49%. Subject to Hydrocarbons Exploration Licensing Policy (HELP).",
    category: "Infrastructure",
  },
  {
    sector: "Defence Manufacturing",
    subsectors: ["Manufacture of defence equipment", "Defence R&D", "Maintenance, repair and overhaul (MRO)"],
    limit: 74,
    route: "Mixed",
    conditions: "Up to 74% via automatic route. Above 74% requires government approval where it is likely to result in access to modern technology or for other reasons to be recorded. FDI in defence sector subject to security conditions, industrial licence under Industries Development and Regulation Act, and MoD guidelines.",
    category: "Defence & Space",
  },
  {
    sector: "Space — Launch Vehicles & Satellites",
    subsectors: ["Satellites (manufacture & operation)", "Launch vehicles", "Spaceports"],
    limit: 74,
    route: "Mixed",
    conditions: "Satellites (manufacture & operation) up to 74% automatic; above 74% government approval. Launch vehicles & spaceports up to 49% automatic; above 49% government. Ground segment and user segment 100% automatic. Subject to ISRO/IN-SPACe/DOS guidelines.",
    category: "Defence & Space",
  },
  // ── Broadcasting & Media ─────────────────────────────────────────────────────
  {
    sector: "Broadcasting — Terrestrial TV (Free-to-Air)",
    subsectors: [],
    limit: 26,
    route: "Government",
    conditions: "Maximum 26% FDI via government approval route. Subject to Ministry of Information & Broadcasting guidelines. Foreign investment includes both FDI and FPI.",
    category: "Media & Entertainment",
  },
  {
    sector: "Broadcasting — FM Radio",
    subsectors: [],
    limit: 26,
    route: "Government",
    conditions: "Maximum 26% FDI via government approval. Subject to information security conditions and MIB guidelines. Foreign investment cap includes FII/FPI.",
    category: "Media & Entertainment",
  },
  {
    sector: "Broadcasting — Cable & Satellite TV (DTH, Cable)",
    subsectors: ["Direct-to-Home (DTH)", "Cable networks", "HITS", "Mobile TV", "Headend-in-the-sky"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for cable and satellite TV. DTH licensees must be an Indian company. Subject to programme and advertising codes.",
    category: "Media & Entertainment",
  },
  {
    sector: "Digital / Online News Media",
    subsectors: ["Digital news portals", "Online news aggregators"],
    limit: 26,
    route: "Government",
    conditions: "Maximum 26% FDI via government approval route for entities that upload or stream news and current affairs. Definition of 'news media' is broad.",
    category: "Media & Entertainment",
  },
  {
    sector: "Print Media — Newspapers & Periodicals (Indian Language)",
    subsectors: ["Newspapers", "Periodicals", "News magazines"],
    limit: 26,
    route: "Government",
    conditions: "Maximum 26% FDI via government approval. Controlled by Ministry of Information & Broadcasting. Subject to guidelines on editorial control.",
    category: "Media & Entertainment",
  },
  {
    sector: "Print Media — Scientific/Technical/Specialty Publications",
    subsectors: ["Scientific journals", "Technical magazines", "Specialty trade publications"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for scientific, technical, and specialty publications not carrying news. MIB registration required.",
    category: "Media & Entertainment",
  },
  // ── Banking & Financial ───────────────────────────────────────────────────────
  {
    sector: "Banking — Private Sector Banks",
    subsectors: ["Scheduled commercial banks (private)", "Small finance banks", "Payment banks"],
    limit: 74,
    route: "Automatic",
    conditions: "Up to 74% via automatic route. Beyond 49% up to 74%, FDI requires government approval only if it results in change of management/ownership. Aggregate foreign investment (FDI + FII/FPI + NRI + FVCI) capped at 74%. Subject to RBI's fit and proper criteria.",
    category: "Financial",
  },
  {
    sector: "Banking — Public Sector Banks",
    subsectors: ["Nationalised banks", "SBI"],
    limit: 20,
    route: "Government",
    conditions: "Maximum 20% aggregate foreign investment (FDI + FII/FPI) via government approval. Subject to Banking Companies (Acquisition & Transfer of Undertakings) Act. Government retains >51% at all times.",
    category: "Financial",
  },
  {
    sector: "Insurance",
    subsectors: ["Life insurance", "General insurance", "Reinsurance", "Insurance brokers", "Third party administrators"],
    limit: 74,
    route: "Automatic",
    conditions: "74% FDI via automatic route (increased from 49% in 2021 Budget). Insurance intermediaries (brokers, surveyors, TPAs) 100% automatic. Subject to IRDAI approval and Indian management/control requirement.",
    category: "Financial",
  },
  {
    sector: "Pension Funds",
    subsectors: [],
    limit: 74,
    route: "Automatic",
    conditions: "Up to 74% via automatic route. Subject to PFRDA Act and regulations. FDI limit same as insurance (74%). Indian management and control required.",
    category: "Financial",
  },
  {
    sector: "Asset Reconstruction Companies (ARC)",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. No FDI limit. FII/FPI can invest up to 100% in Security Receipts (SRs) issued by ARCs. Subject to RBI/SARFAESI Act guidelines.",
    category: "Financial",
  },
  {
    sector: "Non-Banking Finance Companies (NBFC)",
    subsectors: ["Merchant banking", "Underwriting", "Portfolio management", "Investment advisory", "Financial consultancy", "Stock broking", "Custodial services", "Micro credit", "Rural credit"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for NBFC activities listed in Annex B of DPIIT Consolidated FDI Policy. Minimum capitalisation norms as per RBI apply.",
    category: "Financial",
  },
  {
    sector: "Stock Exchanges, Depositories, Clearing Corporations",
    subsectors: [],
    limit: 49,
    route: "Automatic",
    conditions: "FDI + FII/FPI combined up to 49% via automatic route. Any single entity restricted to 5% of paid-up capital. Subject to SEBI approval.",
    category: "Financial",
  },
  {
    sector: "Commodity Exchanges",
    subsectors: [],
    limit: 49,
    route: "Automatic",
    conditions: "FDI up to 26% via automatic route; FII/FPI up to 23% (total 49%). Any single entity limit of 5%. Subject to FMC/SEBI.",
    category: "Financial",
  },
  // ── Telecom ───────────────────────────────────────────────────────────────────
  {
    sector: "Telecom Services",
    subsectors: ["Mobile telephony", "Internet service providers", "National long distance", "International long distance", "Infrastructure providers", "VSAT", "Resale of IPLC"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to DoT licensing conditions, national security safeguards. FDI beyond 49% requires security clearance for certain activities.",
    category: "Technology",
  },
  // ── Civil Aviation ────────────────────────────────────────────────────────────
  {
    sector: "Civil Aviation — Scheduled Air Transport (Domestic Airlines)",
    subsectors: ["Domestic scheduled passenger airlines"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for domestic scheduled airlines. NRI investment: 100% automatic. Foreign airlines can invest up to 49% in Indian airlines directly.",
    category: "Infrastructure",
  },
  {
    sector: "Civil Aviation — Ground Handling Services",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to security considerations and BCAS regulations.",
    category: "Infrastructure",
  },
  {
    sector: "Civil Aviation — Maintenance, Repair & Overhaul (MRO)",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Important for India's aviation MRO ecosystem.",
    category: "Infrastructure",
  },
  {
    sector: "Civil Aviation — Airports (Existing)",
    subsectors: [],
    limit: 74,
    route: "Mixed",
    conditions: "Up to 74% via automatic route; beyond 74% via government approval for existing brownfield airports. Greenfield airports: 100% automatic. Subject to AAI/DGCA regulations.",
    category: "Infrastructure",
  },
  {
    sector: "Civil Aviation — Airports (Greenfield)",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for greenfield airports. Subject to National Civil Aviation Policy and security guidelines.",
    category: "Infrastructure",
  },
  // ── Construction & Real Estate ────────────────────────────────────────────────
  {
    sector: "Construction Development (Townships, Housing, Built-up Infrastructure)",
    subsectors: ["Housing", "Commercial premises", "Hotels", "Resorts", "Hospitals", "Educational institutions", "Recreational facilities", "City/regional level infrastructure"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Minimum area requirement: 20,000 sq. metres for construction development projects. Minimum capitalisation: USD 5 million within 6 months. Lock-in of 3 years on original investment. Repatriation allowed after project completion or 3 years, whichever is earlier.",
    category: "Infrastructure",
  },
  {
    sector: "Real Estate — Earning of Rent/Income on Completed Property",
    subsectors: [],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in real estate business (buying and selling of completed real estate). However, FDI in construction/development activities is permitted separately.",
    category: "Infrastructure",
  },
  {
    sector: "Special Economic Zones (SEZ)",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for setting up SEZs and units within SEZs. Subject to SEZ Act and SEZ Rules.",
    category: "Infrastructure",
  },
  {
    sector: "Industrial Parks",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Must meet criteria as prescribed by Ministry of Commerce (minimum 10 units, common infrastructure, etc.).",
    category: "Infrastructure",
  },
  // ── IT & Technology ────────────────────────────────────────────────────────────
  {
    sector: "IT & IT-Enabled Services (IT/ITES)",
    subsectors: ["Software development", "BPO", "KPO", "Data centres", "IT consulting", "Software products", "Cloud computing"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. No sectoral restrictions. One of the most liberal FDI sectors. Subject to general laws (Companies Act, FEMA).",
    category: "Technology",
  },
  {
    sector: "E-Commerce — Marketplace Model",
    subsectors: ["Online retail marketplace", "B2B e-commerce"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for marketplace-based e-commerce. Marketplace entity cannot directly/indirectly influence price. Cannot have more than 25% sales from a single vendor/group. Must not require vendors to sell exclusively on its platform. B2B e-commerce: 100% automatic.",
    category: "Retail & Commerce",
  },
  {
    sector: "E-Commerce — Inventory-Based Model",
    subsectors: [],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in inventory-based e-commerce model where entity owns the inventory and sells directly to consumers.",
    category: "Retail & Commerce",
  },
  // ── Retail ────────────────────────────────────────────────────────────────────
  {
    sector: "Single Brand Retail Trading (SBRT)",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Products must be sold under the same brand internationally. For FDI above 51%, mandatory local sourcing of 30% from Indian micro, small, and cottage industries (averaged over 5 years). Subject to DIPP guidelines.",
    category: "Retail & Commerce",
  },
  {
    sector: "Multi Brand Retail Trading (MBRT)",
    subsectors: [],
    limit: 51,
    route: "Government",
    conditions: "Maximum 51% FDI via government approval. Minimum investment of USD 100 million. 50% of investment in backend infrastructure. Mandatory 30% sourcing from Indian SMEs (initial). Only in cities with population >1 million (as per 2011 census). State government consent required.",
    category: "Retail & Commerce",
  },
  {
    sector: "Cash & Carry Wholesale Trading",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for wholesale trading. Sales only to retailers, industrial/commercial users, institutional buyers — not to end consumers.",
    category: "Retail & Commerce",
  },
  {
    sector: "Duty Free Shops",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Sales permitted only at international ports/airports to outbound international travellers.",
    category: "Retail & Commerce",
  },
  // ── Pharma & Healthcare ───────────────────────────────────────────────────────
  {
    sector: "Pharmaceuticals — Greenfield",
    subsectors: ["New pharmaceutical manufacturing units"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for greenfield pharmaceutical projects. Subject to DPIIT, Ministry of Chemicals & Fertilizers guidelines.",
    category: "Manufacturing",
  },
  {
    sector: "Pharmaceuticals — Brownfield",
    subsectors: ["Acquisition/expansion of existing pharmaceutical units"],
    limit: 100,
    route: "Mixed",
    conditions: "Up to 74% via automatic route. Beyond 74% via government approval route. CDSCO and Ministry of Health approval required. Government examines impact on drug accessibility, pricing, and availability of essential medicines.",
    category: "Manufacturing",
  },
  {
    sector: "Medical Devices",
    subsectors: ["Surgical instruments", "Diagnostic equipment", "Implants", "In-vitro diagnostics"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to Drugs and Cosmetics Act (for devices) and Medical Devices Rules 2017.",
    category: "Manufacturing",
  },
  {
    sector: "Hospitals & Healthcare Services",
    subsectors: ["Multi-speciality hospitals", "Specialty clinics", "Diagnostic centres"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to Clinical Establishments Act and state-level regulations. Foreign doctors must be registered with Medical Council of India.",
    category: "Services",
  },
  // ── Manufacturing ─────────────────────────────────────────────────────────────
  {
    sector: "Food Processing Industries",
    subsectors: ["Fruits and vegetables processing", "Dairy", "Fisheries", "Meat and poultry", "Food packaging"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. For food products manufactured and produced in India sold through e-commerce: 100% automatic route through FIPB (now DPIIT). Food Retail (trading of food products produced in India): 100% automatic.",
    category: "Manufacturing",
  },
  {
    sector: "Food Retail (Trading of India-made food products)",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for retail trading of food products manufactured and produced in India, including through e-commerce. Government approval may be required depending on structure.",
    category: "Retail & Commerce",
  },
  {
    sector: "Electronics & Hardware Manufacturing",
    subsectors: ["Electronic components", "Semiconductors", "Consumer electronics", "Industrial electronics"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Eligible for PLI schemes. Subject to BIS standards and import restrictions on certain components.",
    category: "Manufacturing",
  },
  {
    sector: "Automobile & Auto Components",
    subsectors: ["Passenger vehicles", "Commercial vehicles", "Two-wheelers", "Auto components", "EV manufacturing"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to Automotive Mission Plan guidelines. EV-specific manufacturing benefits under PLI scheme.",
    category: "Manufacturing",
  },
  {
    sector: "Textiles & Garments",
    subsectors: ["Yarn", "Fabric", "Garments", "Technical textiles"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to Textile Policy and PLI scheme for man-made fibres and technical textiles.",
    category: "Manufacturing",
  },
  {
    sector: "Chemical Industry",
    subsectors: ["Basic chemicals", "Specialty chemicals", "Dyes and pigments", "Pesticides"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route except for hazardous chemicals requiring industrial licence. Subject to Environmental regulations and Factories Act.",
    category: "Manufacturing",
  },
  // ── Energy & Infrastructure ───────────────────────────────────────────────────
  {
    sector: "Renewable Energy",
    subsectors: ["Solar power", "Wind energy", "Biomass energy", "Hydro power (small)", "Green hydrogen"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to CERC/SERC regulations and Power Purchase Agreements. RPO obligations apply to the grid.",
    category: "Infrastructure",
  },
  {
    sector: "Power (Generation, Transmission, Distribution)",
    subsectors: ["Thermal power", "Gas-based power", "Transmission lines", "Distribution networks"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to Electricity Act 2003, CERC regulations, and state electricity board regulations. Nuclear power is prohibited to private/foreign entities.",
    category: "Infrastructure",
  },
  {
    sector: "Logistics & Warehousing",
    subsectors: ["Courier services", "Cold chain logistics", "Warehousing", "Third-party logistics (3PL)", "Freight forwarding"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Courier services: 100% automatic. Subject to Carriage by Air Act, Carriage by Road Act. Defence establishment areas excluded.",
    category: "Infrastructure",
  },
  {
    sector: "Ports & Shipping",
    subsectors: ["Port construction", "Port operations", "Shipping services"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for port and harbour construction and maintenance. Subject to Port Trust regulations and Indian Ports Act.",
    category: "Infrastructure",
  },
  {
    sector: "Railways (excluding operations)",
    subsectors: ["Railway infrastructure", "Suburban corridor projects", "High-speed rail", "Dedicated freight corridors", "Railway electrification"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route for railway infrastructure. Railway operations (passenger/freight train operations on own network) remain with Indian Railways (prohibited for FDI).",
    category: "Infrastructure",
  },
  {
    sector: "Roads & Highways",
    subsectors: ["Road construction", "Toll roads", "BOT projects"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to NHAI concession agreement terms and MoRTH guidelines.",
    category: "Infrastructure",
  },
  // ── Services ─────────────────────────────────────────────────────────────────
  {
    sector: "Hotels & Tourism",
    subsectors: ["Hotels", "Resorts", "Travel agencies", "Tourism services"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to state-level tourism and excise regulations.",
    category: "Services",
  },
  {
    sector: "Education",
    subsectors: ["School education", "Higher education", "Vocational training", "Skill development"],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Non-profit educational institutions have specific conditionalities. Must comply with AICTE, UGC, MCI regulations as applicable.",
    category: "Services",
  },
  // ── White Label ATM ───────────────────────────────────────────────────────────
  {
    sector: "White Label ATM Operations",
    subsectors: [],
    limit: 100,
    route: "Automatic",
    conditions: "100% FDI via automatic route. Subject to RBI guidelines for White Label ATM Operators (WLAO). Minimum net worth of Rs. 100 crore required.",
    category: "Financial",
  },
  // ── Prohibited Sectors ────────────────────────────────────────────────────────
  {
    sector: "Lottery Business",
    subsectors: ["Online lottery", "Private lottery", "Government lottery"],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in lottery business, including government/private lottery, online lotteries, etc.",
    category: "Services",
  },
  {
    sector: "Gambling & Betting",
    subsectors: ["Casinos", "Sports betting", "Online gambling"],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in gambling and betting activities including casinos. Online gaming regulations being developed separately.",
    category: "Services",
  },
  {
    sector: "Chit Funds",
    subsectors: [],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in chit fund business. Regulated under Chit Funds Act 1982.",
    category: "Financial",
  },
  {
    sector: "Nidhi Companies",
    subsectors: [],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted. Nidhi companies can only accept deposits from and lend to their members.",
    category: "Financial",
  },
  {
    sector: "Trading in Transferable Development Rights (TDR)",
    subsectors: [],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in trading in transferable development rights.",
    category: "Infrastructure",
  },
  {
    sector: "Tobacco / Cigarettes Manufacturing",
    subsectors: ["Cigarettes", "Cigars", "Cheroots", "Bidis"],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in manufacturing of cigars, cheroots, cigarillos, cigarettes, whether of tobacco or tobacco substitutes.",
    category: "Manufacturing",
  },
  {
    sector: "Nuclear Power / Atomic Energy",
    subsectors: [],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted. Atomic Energy Act 1962 prohibits private/foreign participation in nuclear power generation and supply of nuclear fuel.",
    category: "Infrastructure",
  },
  {
    sector: "Railway Operations (Freight & Passenger)",
    subsectors: ["Operating freight trains", "Passenger rail services"],
    limit: 0,
    route: "Prohibited",
    conditions: "FDI not permitted in railway transport operations. Only railway infrastructure (construction, electrification, rolling stock manufacturing) is open.",
    category: "Infrastructure",
  },
];
