// India DTAA Treaty Rates — based on publicly available CBDT notifications.
// Rates shown are treaty rates; domestic withholding rates may differ.
// Always verify with the latest CBDT notifications and MLI synthesised text.

export const DTAA_COUNTRIES = [
  {
    country: "Australia",
    flag: "🇦🇺",
    region: "Asia-Pacific",
    div: "15%",
    int: "15%",
    roy: "10%/15%",
    fts: "10%/15%",
    trc: true,
    notes: "FTS rate 10% for make-available; 15% otherwise. MLI in force. PPT applies.",
  },
  {
    country: "Austria",
    flag: "🇦🇹",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Protocol updated in 2001.",
  },
  {
    country: "Bangladesh",
    flag: "🇧🇩",
    region: "South Asia",
    div: "10%/15%",
    int: "10%",
    roy: "10%",
    fts: "N/A",
    trc: true,
    notes: "10% dividend if >10% holding; 15% otherwise. Treaty predates MLI.",
  },
  {
    country: "Bahrain",
    flag: "🇧🇭",
    region: "Middle East",
    div: "N/A",
    int: "N/A",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Limited treaty — covers royalties and FTS only. No withholding on dividends/interest.",
  },
  {
    country: "Belarus",
    flag: "🇧🇾",
    region: "Europe",
    div: "10%/15%",
    int: "10%",
    roy: "15%",
    fts: "15%",
    trc: true,
    notes: "10% dividend for >25% holding; 15% otherwise. Treaty signed 1997.",
  },
  {
    country: "Belgium",
    flag: "🇧🇪",
    region: "Europe",
    div: "15%",
    int: "15%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT and SLOB apply. Protocol revised 1993.",
  },
  {
    country: "Brazil",
    flag: "🇧🇷",
    region: "Americas",
    div: "15%",
    int: "15%",
    roy: "15%/25%",
    fts: "N/A",
    trc: true,
    notes: "No DTAA in force — domestic rates apply. Withholding at 15% standard; 25% for tax haven remittances.",
  },
  {
    country: "Canada",
    flag: "🇨🇦",
    region: "Americas",
    div: "15%/25%",
    int: "15%",
    roy: "10%/15%",
    fts: "10%/15%",
    trc: true,
    notes: "15% dividend for >10% voting shares; 25% otherwise. FTS 10% if make-available, else 15%. MLI in force.",
  },
  {
    country: "China",
    flag: "🇨🇳",
    region: "Asia-Pacific",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Revised treaty effective 2018. MLI not applicable (bilateral renegotiation used).",
  },
  {
    country: "Cyprus",
    flag: "🇨🇾",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Revised DTAA effective 2017. Earlier treaty notified as Limited; new treaty has LOB-type clause.",
  },
  {
    country: "Czech Republic",
    flag: "🇨🇿",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty signed 1998.",
  },
  {
    country: "Denmark",
    flag: "🇩🇰",
    region: "Europe",
    div: "15%/25%",
    int: "15%",
    roy: "20%",
    fts: "20%",
    trc: true,
    notes: "MLI in force. PPT applies. Older treaty — royalty rate 20%.",
  },
  {
    country: "Egypt",
    flag: "🇪🇬",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No comprehensive DTAA in force. Limited agreement on air transport only.",
  },
  {
    country: "Ethiopia",
    flag: "🇪🇹",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force. Domestic Indian withholding rates apply.",
  },
  {
    country: "Finland",
    flag: "🇫🇮",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Revised treaty effective 2012.",
  },
  {
    country: "France",
    flag: "🇫🇷",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Revised treaty effective 1994; protocol added 2000.",
  },
  {
    country: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Updated protocol 1996. One of India's most used treaties.",
  },
  {
    country: "Greece",
    flag: "🇬🇷",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force. Domestic Indian withholding rates apply.",
  },
  {
    country: "Hong Kong",
    flag: "🇭🇰",
    region: "Asia-Pacific",
    div: "5%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "DTAA effective 2018. 5% dividend for >10% holding. LOB article included.",
  },
  {
    country: "Hungary",
    flag: "🇭🇺",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies.",
  },
  {
    country: "Indonesia",
    flag: "🇮🇩",
    region: "Asia-Pacific",
    div: "10%",
    int: "10%",
    roy: "15%",
    fts: "N/A",
    trc: true,
    notes: "No specific FTS article; may fall under royalties. Treaty signed 1987.",
  },
  {
    country: "Ireland",
    flag: "🇮🇪",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Important for technology and financial services.",
  },
  {
    country: "Israel",
    flag: "🇮🇱",
    region: "Middle East",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Treaty signed 1996, effective 1994. No MLI.",
  },
  {
    country: "Italy",
    flag: "🇮🇹",
    region: "Europe",
    div: "15%/25%",
    int: "15%",
    roy: "20%",
    fts: "20%",
    trc: true,
    notes: "MLI in force. PPT applies. Older treaty — higher royalty rate.",
  },
  {
    country: "Japan",
    flag: "🇯🇵",
    region: "Asia-Pacific",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Revised treaty effective 2007. MLI in force. PPT applies. Key for Japanese investments in India.",
  },
  {
    country: "Jordan",
    flag: "🇯🇴",
    region: "Middle East",
    div: "10%",
    int: "10%",
    roy: "20%",
    fts: "20%",
    trc: true,
    notes: "Treaty signed 1999. No MLI. Royalty rate relatively high at 20%.",
  },
  {
    country: "Kazakhstan",
    flag: "🇰🇿",
    region: "Central Asia",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Treaty effective 1997. No MLI currently.",
  },
  {
    country: "Kenya",
    flag: "🇰🇪",
    region: "Africa",
    div: "15%",
    int: "15%",
    roy: "20%",
    fts: "17.5%",
    trc: true,
    notes: "Treaty signed 1985. No MLI. One of few Africa DTAAs India has.",
  },
  {
    country: "South Korea",
    flag: "🇰🇷",
    region: "Asia-Pacific",
    div: "15%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Important for Korean manufacturing investments.",
  },
  {
    country: "Kuwait",
    flag: "🇰🇼",
    region: "Middle East",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Treaty effective 2008. No MLI. Key for Kuwaiti sovereign wealth flows.",
  },
  {
    country: "Latvia",
    flag: "🇱🇻",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies.",
  },
  {
    country: "Lithuania",
    flag: "🇱🇹",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies.",
  },
  {
    country: "Luxembourg",
    flag: "🇱🇺",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Key for European fund structures.",
  },
  {
    country: "Malaysia",
    flag: "🇲🇾",
    region: "Asia-Pacific",
    div: "N/A",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "No withholding on dividends (exemption method). Treaty signed 1976, amended 2012.",
  },
  {
    country: "Malta",
    flag: "🇲🇹",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty effective 1994.",
  },
  {
    country: "Mauritius",
    flag: "🇲🇺",
    region: "Africa",
    div: "5%/15%",
    int: "7.5%",
    roy: "15%",
    fts: "N/A",
    trc: true,
    notes: "Revised DTAA effective 2017. 5% dividend for >10% shareholding. Capital gains on shares acquired after 1 Apr 2017 taxable in India. TRC mandatory. Grandfathering until 31 Mar 2019.",
  },
  {
    country: "Mexico",
    flag: "🇲🇽",
    region: "Americas",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Treaty effective 2010. MLI in force. PPT applies.",
  },
  {
    country: "Mongolia",
    flag: "🇲🇳",
    region: "Asia-Pacific",
    div: "15%",
    int: "15%",
    roy: "15%",
    fts: "N/A",
    trc: true,
    notes: "Treaty signed 1994. No MLI.",
  },
  {
    country: "Morocco",
    flag: "🇲🇦",
    region: "Africa",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Treaty signed 1999, effective 1999. No MLI.",
  },
  {
    country: "Myanmar",
    flag: "🇲🇲",
    region: "Asia-Pacific",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No comprehensive DTAA in force.",
  },
  {
    country: "Nepal",
    flag: "🇳🇵",
    region: "South Asia",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No comprehensive DTAA in force. Limited air services agreement only.",
  },
  {
    country: "Netherlands",
    flag: "🇳🇱",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Key conduit country; stricter PPT means treaty shopping harder. Updated 2012.",
  },
  {
    country: "New Zealand",
    flag: "🇳🇿",
    region: "Asia-Pacific",
    div: "15%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty effective 1986.",
  },
  {
    country: "Norway",
    flag: "🇳🇴",
    region: "Europe",
    div: "15%/25%",
    int: "15%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Older treaty.",
  },
  {
    country: "Oman",
    flag: "🇴🇲",
    region: "Middle East",
    div: "10%/12.5%",
    int: "10%",
    roy: "15%",
    fts: "15%",
    trc: true,
    notes: "10% dividend for >10% holding; 12.5% otherwise. Treaty effective 1997.",
  },
  {
    country: "Philippines",
    flag: "🇵🇭",
    region: "Asia-Pacific",
    div: "15%/20%",
    int: "10%/15%",
    roy: "15%",
    fts: "N/A",
    trc: true,
    notes: "15% dividend if >10% holding, 20% otherwise. Interest 10% for government/bank; 15% others. No MLI.",
  },
  {
    country: "Poland",
    flag: "🇵🇱",
    region: "Europe",
    div: "15%",
    int: "15%",
    roy: "22.5%",
    fts: "22.5%",
    trc: true,
    notes: "MLI in force. PPT applies. Older treaty — high royalty rate. Protocol signed 2013.",
  },
  {
    country: "Portugal",
    flag: "🇵🇹",
    region: "Europe",
    div: "10%/15%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty effective 2010.",
  },
  {
    country: "Qatar",
    flag: "🇶🇦",
    region: "Middle East",
    div: "5%/10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "5% dividend for >10% holding; 10% otherwise. Treaty effective 2000. Key for Qatar Investment Authority flows.",
  },
  {
    country: "Romania",
    flag: "🇷🇴",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "Treaty being renegotiated. Older treaty (1987) has limited applicability.",
  },
  {
    country: "Russia",
    flag: "🇷🇺",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty revised 1997. Recent geopolitical developments may affect applicability.",
  },
  {
    country: "Saudi Arabia",
    flag: "🇸🇦",
    region: "Middle East",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No comprehensive DTAA. Limited investment protection agreement exists. Negotiations ongoing.",
  },
  {
    country: "Singapore",
    flag: "🇸🇬",
    region: "Asia-Pacific",
    div: "10%/15%",
    int: "10%/15%",
    roy: "10%/15%",
    fts: "10%/15%",
    trc: true,
    notes: "Revised DTAA effective 2017. 10% rates require meeting LOB conditions (active business, listed entity, etc.). Capital gains on shares acquired after 1 Apr 2017 taxable in India. PPT now applies via MLI.",
  },
  {
    country: "Slovenia",
    flag: "🇸🇮",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "Treaty signed but not yet in force.",
  },
  {
    country: "South Africa",
    flag: "🇿🇦",
    region: "Africa",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty effective 1998.",
  },
  {
    country: "Spain",
    flag: "🇪🇸",
    region: "Europe",
    div: "15%",
    int: "15%",
    roy: "10%/20%",
    fts: "10%/20%",
    trc: true,
    notes: "MLI in force. PPT applies. 10% royalty for equipment royalties; 20% others.",
  },
  {
    country: "Sri Lanka",
    flag: "🇱🇰",
    region: "South Asia",
    div: "7.5%/15%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "7.5% dividend for >10% holding; 15% otherwise. Treaty signed 2013, effective 2016.",
  },
  {
    country: "Sweden",
    flag: "🇸🇪",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. Treaty revised 1997.",
  },
  {
    country: "Switzerland",
    flag: "🇨🇭",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies. MFN clause triggered — rates reduced to 10% after Mauritius/Slovenia treaties. Key for pharma and financial sector.",
  },
  {
    country: "Tanzania",
    flag: "🇹🇿",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Thailand",
    flag: "🇹🇭",
    region: "Asia-Pacific",
    div: "10%",
    int: "10%/25%",
    roy: "10%/15%",
    fts: "N/A",
    trc: true,
    notes: "Interest 10% for banks/financial institutions; 25% others. Royalty 10% for equipment; 15% others. No MLI.",
  },
  {
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    region: "Americas",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Turkey",
    flag: "🇹🇷",
    region: "Europe",
    div: "15%",
    int: "10%/15%",
    roy: "15%",
    fts: "15%",
    trc: true,
    notes: "MLI in force. PPT applies. Interest 10% for financial institutions; 15% others.",
  },
  {
    country: "UAE",
    flag: "🇦🇪",
    region: "Middle East",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: true,
    notes: "Existing DTAA covers air transport only. UAE does not levy personal income tax — comprehensive DTAA being negotiated. Domestic withholding rates apply for royalties etc.",
  },
  {
    country: "UK",
    flag: "🇬🇧",
    region: "Europe",
    div: "15%",
    int: "15%",
    roy: "15%",
    fts: "15%",
    trc: true,
    notes: "MLI in force. PPT applies. Original treaty 1981; Protocol 1993. UK-India renegotiation ongoing post-Brexit. 15% cap on most payments.",
  },
  {
    country: "Ukraine",
    flag: "🇺🇦",
    region: "Europe",
    div: "10%/15%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "10% dividend for >25% holding; 15% otherwise. Treaty effective 1999.",
  },
  {
    country: "USA",
    flag: "🇺🇸",
    region: "Americas",
    div: "15%/25%",
    int: "15%",
    roy: "10%/15%",
    fts: "10%/15%",
    trc: true,
    notes: "15% dividend for >10% voting; 25% otherwise. FTS 10% for make-available; 15% otherwise. USA has not adopted MLI. Treaty signed 1989. LOB article in treaty.",
  },
  {
    country: "Uzbekistan",
    flag: "🇺🇿",
    region: "Central Asia",
    div: "15%",
    int: "15%",
    roy: "15%",
    fts: "N/A",
    trc: true,
    notes: "Treaty signed 1994. No MLI.",
  },
  {
    country: "Vietnam",
    flag: "🇻🇳",
    region: "Asia-Pacific",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "Treaty effective 1995. No MLI. Important for India-Vietnam manufacturing corridor.",
  },
  {
    country: "Zambia",
    flag: "🇿🇲",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Argentina",
    flag: "🇦🇷",
    region: "Americas",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force. Domestic Indian withholding rates apply.",
  },
  {
    country: "Estonia",
    flag: "🇪🇪",
    region: "Europe",
    div: "10%",
    int: "10%",
    roy: "10%",
    fts: "10%",
    trc: true,
    notes: "MLI in force. PPT applies.",
  },
  {
    country: "Slovakia",
    flag: "🇸🇰",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "Treaty with former Czechoslovakia applies; applicability debated. Renegotiation pending.",
  },
  {
    country: "Croatia",
    flag: "🇭🇷",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Serbia",
    flag: "🇷🇸",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "Treaty with former Yugoslavia may apply; status uncertain. Renegotiation recommended.",
  },
  {
    country: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    region: "Europe",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Kyrgyzstan",
    flag: "🇰🇬",
    region: "Central Asia",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Armenia",
    flag: "🇦🇲",
    region: "Central Asia",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Georgia",
    flag: "🇬🇪",
    region: "Central Asia",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Azerbaijan",
    flag: "🇦🇿",
    region: "Central Asia",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force. Negotiations reported.",
  },
  {
    country: "Pakistan",
    flag: "🇵🇰",
    region: "South Asia",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "DTAA suspended. Domestic rates apply. See Section 90 of Income Tax Act.",
  },
  {
    country: "Ghana",
    flag: "🇬🇭",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Nigeria",
    flag: "🇳🇬",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force. Negotiations ongoing.",
  },
  {
    country: "Algeria",
    flag: "🇩🇿",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Tunisia",
    flag: "🇹🇳",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Libya",
    flag: "🇱🇾",
    region: "Africa",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Cambodia",
    flag: "🇰🇭",
    region: "Asia-Pacific",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
  {
    country: "Myanmar",
    flag: "🇲🇲",
    region: "Asia-Pacific",
    div: "N/A",
    int: "N/A",
    roy: "N/A",
    fts: "N/A",
    trc: false,
    notes: "No DTAA in force.",
  },
];
