// ─── HSN Headings: 4-digit and 6-digit codes ─────────────────────────────────
// Source: CBIC GST tariff schedule (India HSN 2022 edition)
// Covers all 99 chapters at 4-digit level; major chapters at 6-digit level.

export const HSN_HEADINGS = [

  // ── Chapter 01: Live animals ──────────────────────────────────────────────
  { code: '0101', desc: 'Live horses, asses, mules and hinnies', ch: '01' },
  { code: '0102', desc: 'Live bovine animals', ch: '01' },
  { code: '0103', desc: 'Live swine', ch: '01' },
  { code: '0104', desc: 'Live sheep and goats', ch: '01' },
  { code: '0105', desc: 'Live poultry (fowls, ducks, geese, turkeys, guinea fowls)', ch: '01' },
  { code: '0106', desc: 'Other live animals (mammals, birds, reptiles, insects, etc.)', ch: '01' },

  // ── Chapter 02: Meat ──────────────────────────────────────────────────────
  { code: '0201', desc: 'Meat of bovine animals, fresh or chilled', ch: '02' },
  { code: '0202', desc: 'Meat of bovine animals, frozen', ch: '02' },
  { code: '0203', desc: 'Meat of swine, fresh, chilled or frozen', ch: '02' },
  { code: '0204', desc: 'Meat of sheep or goats, fresh, chilled or frozen', ch: '02' },
  { code: '0207', desc: 'Meat and edible offal, of poultry', ch: '02' },
  { code: '0210', desc: 'Meat and edible meat offal, salted, in brine, dried or smoked', ch: '02' },

  // ── Chapter 03: Fish ──────────────────────────────────────────────────────
  { code: '0301', desc: 'Live fish', ch: '03' },
  { code: '0302', desc: 'Fish, fresh or chilled (excluding fillets)', ch: '03' },
  { code: '0303', desc: 'Fish, frozen (excluding fillets)', ch: '03' },
  { code: '0304', desc: 'Fish fillets and other fish meat', ch: '03' },
  { code: '0305', desc: 'Fish, dried, salted or in brine; smoked fish', ch: '03' },
  { code: '0306', desc: 'Crustaceans (shrimps, prawns, lobsters, crabs)', ch: '03' },
  { code: '0307', desc: 'Molluscs (oysters, scallops, mussels, cuttlefish, squid)', ch: '03' },

  // ── Chapter 04: Dairy ─────────────────────────────────────────────────────
  { code: '0401', desc: 'Milk and cream, not concentrated nor sweetened', ch: '04' },
  { code: '0402', desc: 'Milk and cream, concentrated or sweetened', ch: '04' },
  { code: '0403', desc: 'Buttermilk, curdled milk, cream, yogurt, kephir', ch: '04' },
  { code: '0404', desc: 'Whey, whether or not concentrated or sweetened', ch: '04' },
  { code: '0405', desc: 'Butter and other fats and oils derived from milk; dairy spreads', ch: '04' },
  { code: '0406', desc: 'Cheese and curd', ch: '04' },
  { code: '0407', desc: 'Birds\' eggs, in shell, fresh, preserved or cooked', ch: '04' },
  { code: '0409', desc: 'Natural honey', ch: '04' },

  // ── Chapter 07: Vegetables ────────────────────────────────────────────────
  { code: '0701', desc: 'Potatoes, fresh or chilled', ch: '07' },
  { code: '0702', desc: 'Tomatoes, fresh or chilled', ch: '07' },
  { code: '0703', desc: 'Onions, shallots, garlic, leeks and other alliaceous vegetables', ch: '07' },
  { code: '0704', desc: 'Cabbages, cauliflowers, kohlrabi, kale and similar edible brassicas', ch: '07' },
  { code: '0706', desc: 'Carrots, turnips, salad beetroot, radishes and similar edible roots', ch: '07' },
  { code: '0709', desc: 'Other vegetables, fresh or chilled (capsicum, okra, etc.)', ch: '07' },
  { code: '0713', desc: 'Dried leguminous vegetables (lentils, chickpeas, beans, peas)', ch: '07' },
  { code: '0714', desc: 'Manioc, arrowroot, sweet potatoes and similar roots (tapioca)', ch: '07' },

  // ── Chapter 08: Fruit and Nuts ────────────────────────────────────────────
  { code: '0801', desc: 'Coconuts, Brazil nuts, cashew nuts', ch: '08' },
  { code: '0802', desc: 'Other nuts (almonds, hazelnuts, walnuts, pistachios)', ch: '08' },
  { code: '0803', desc: 'Bananas, including plantains, fresh or dried', ch: '08' },
  { code: '0804', desc: 'Dates, figs, pineapples, avocados, guavas, mangoes', ch: '08' },
  { code: '0805', desc: 'Citrus fruit — oranges, mandarins, lemons, grapefruit', ch: '08' },
  { code: '0806', desc: 'Grapes, fresh or dried (raisins)', ch: '08' },
  { code: '0808', desc: 'Apples, pears and quinces, fresh', ch: '08' },

  // ── Chapter 09: Coffee, Tea, Spices ───────────────────────────────────────
  { code: '0901', desc: 'Coffee, whether or not roasted or decaffeinated', ch: '09' },
  { code: '0902', desc: 'Tea, whether or not flavoured', ch: '09' },
  { code: '0904', desc: 'Pepper (genus Piper); dried or crushed chillies and capsicums', ch: '09' },
  { code: '0906', desc: 'Cinnamon and cinnamon-tree flowers', ch: '09' },
  { code: '0907', desc: 'Cloves (whole fruit, cloves and stems)', ch: '09' },
  { code: '0908', desc: 'Nutmeg, mace and cardamoms', ch: '09' },
  { code: '0909', desc: 'Seeds of anise, badian, fennel, coriander, cumin, caraway', ch: '09' },
  { code: '0910', desc: 'Ginger, saffron, turmeric, thyme, bay leaves, curry', ch: '09' },

  // ── Chapter 10: Cereals ───────────────────────────────────────────────────
  { code: '1001', desc: 'Wheat and meslin', ch: '10' },
  { code: '1002', desc: 'Rye', ch: '10' },
  { code: '1003', desc: 'Barley', ch: '10' },
  { code: '1004', desc: 'Oats', ch: '10' },
  { code: '1005', desc: 'Maize (corn)', ch: '10' },
  { code: '1006', desc: 'Rice', ch: '10' },
  { code: '100610', desc: 'Rice in the husk (paddy or rough)', ch: '10' },
  { code: '100620', desc: 'Husked (brown) rice', ch: '10' },
  { code: '100630', desc: 'Semi-milled or wholly milled rice', ch: '10' },
  { code: '100640', desc: 'Broken rice', ch: '10' },
  { code: '1007', desc: 'Grain sorghum', ch: '10' },
  { code: '1008', desc: 'Buckwheat, millet, canary seed; other cereals (ragi, jowar)', ch: '10' },

  // ── Chapter 11: Milling products ──────────────────────────────────────────
  { code: '1101', desc: 'Wheat or meslin flour', ch: '11' },
  { code: '1102', desc: 'Cereal flours other than wheat or meslin (maize, rice, rye)', ch: '11' },
  { code: '1103', desc: 'Cereal groats, meal and pellets', ch: '11' },
  { code: '1104', desc: 'Cereal grains otherwise worked (rolled, flaked, pearled)', ch: '11' },
  { code: '1107', desc: 'Malt, whether or not roasted', ch: '11' },
  { code: '1108', desc: 'Starches; inulin', ch: '11' },

  // ── Chapter 15: Fats and oils ─────────────────────────────────────────────
  { code: '1507', desc: 'Soya-bean oil and its fractions', ch: '15' },
  { code: '1508', desc: 'Ground-nut oil and its fractions', ch: '15' },
  { code: '1509', desc: 'Olive oil and its fractions', ch: '15' },
  { code: '1511', desc: 'Palm oil and its fractions', ch: '15' },
  { code: '1512', desc: 'Sunflower-seed, safflower or cotton-seed oil', ch: '15' },
  { code: '1513', desc: 'Coconut (copra) oil, palm kernel or babassu oil', ch: '15' },
  { code: '1514', desc: 'Rape, colza or mustard oil and their fractions', ch: '15' },
  { code: '1516', desc: 'Animal or vegetable fats and oils, hydrogenated (vanaspati)', ch: '15' },

  // ── Chapter 17: Sugar ─────────────────────────────────────────────────────
  { code: '1701', desc: 'Cane or beet sugar and chemically pure sucrose, in solid form', ch: '17' },
  { code: '170111', desc: 'Raw cane sugar', ch: '17' },
  { code: '170112', desc: 'Raw beet sugar', ch: '17' },
  { code: '170191', desc: 'Refined sugar containing added flavouring or colouring matter', ch: '17' },
  { code: '170199', desc: 'Other refined sugar', ch: '17' },
  { code: '1702', desc: 'Other sugars (lactose, maltose, glucose, fructose)', ch: '17' },
  { code: '1703', desc: 'Molasses resulting from extraction or refining of sugar', ch: '17' },
  { code: '1704', desc: 'Sugar confectionery (including white chocolate), not containing cocoa', ch: '17' },

  // ── Chapter 22: Beverages ─────────────────────────────────────────────────
  { code: '2201', desc: 'Waters, including natural or artificial mineral waters; ice and snow', ch: '22' },
  { code: '2202', desc: 'Waters, with added sugar, sweetening matter or flavoured; other non-alcoholic beverages', ch: '22' },
  { code: '2203', desc: 'Beer made from malt', ch: '22' },
  { code: '2204', desc: 'Wine of fresh grapes, including fortified wines', ch: '22' },
  { code: '2207', desc: 'Undenatured ethyl alcohol of ≥80% alcoholic strength', ch: '22' },
  { code: '2208', desc: 'Undenatured ethyl alcohol <80%; spirits, liqueurs and other spirituous beverages', ch: '22' },
  { code: '2209', desc: 'Vinegar and substitutes for vinegar', ch: '22' },

  // ── Chapter 24: Tobacco ───────────────────────────────────────────────────
  { code: '2401', desc: 'Unmanufactured tobacco; tobacco refuse', ch: '24' },
  { code: '2402', desc: 'Cigars, cheroots, cigarillos and cigarettes', ch: '24' },
  { code: '2403', desc: 'Other manufactured tobacco and tobacco substitutes', ch: '24' },

  // ── Chapter 25: Salt, sulphur, earths ─────────────────────────────────────
  { code: '2501', desc: 'Salt; pure sodium chloride', ch: '25' },
  { code: '2502', desc: 'Unroasted iron pyrites', ch: '25' },
  { code: '2503', desc: 'Sulphur of all kinds', ch: '25' },
  { code: '2504', desc: 'Natural graphite', ch: '25' },
  { code: '2505', desc: 'Natural sands of all kinds', ch: '25' },
  { code: '2506', desc: 'Quartz; quartzite', ch: '25' },
  { code: '2507', desc: 'Kaolin and other kaolinic clays', ch: '25' },
  { code: '2515', desc: 'Marble, travertine, alabaster and other calcareous monumental or building stone', ch: '25' },
  { code: '2516', desc: 'Granite, porphyry, basalt, sandstone and other monumental or building stone', ch: '25' },
  { code: '2517', desc: 'Pebbles, gravel, broken or crushed stone for concrete aggregates', ch: '25' },
  { code: '2523', desc: 'Portland cement, aluminous cement, slag cement, supersulphate cement', ch: '25' },
  { code: '252310', desc: 'Cement clinkers', ch: '25' },
  { code: '252321', desc: 'White Portland cement', ch: '25' },
  { code: '252329', desc: 'Other Portland cement', ch: '25' },

  // ── Chapter 27: Mineral fuels ─────────────────────────────────────────────
  { code: '2701', desc: 'Coal; briquettes, ovoids and similar solid fuels manufactured from coal', ch: '27' },
  { code: '270111', desc: 'Anthracite', ch: '27' },
  { code: '270112', desc: 'Bituminous coal', ch: '27' },
  { code: '270119', desc: 'Other coal', ch: '27' },
  { code: '2702', desc: 'Lignite, whether or not agglomerated (excluding jet)', ch: '27' },
  { code: '2704', desc: 'Coke and semi-coke of coal, of lignite or of peat', ch: '27' },
  { code: '2709', desc: 'Petroleum oils and oils obtained from bituminous minerals, crude', ch: '27' },
  { code: '2710', desc: 'Petroleum oils (not crude); preparations not elsewhere specified', ch: '27' },
  { code: '271011', desc: 'Motor spirit (petrol)', ch: '27' },
  { code: '271012', desc: 'Aviation spirit', ch: '27' },
  { code: '271019', desc: 'Other light oils and preparations', ch: '27' },
  { code: '271020', desc: 'Petroleum oils and preparations (medium oils)', ch: '27' },
  { code: '271041', desc: 'Aviation turbine fuel (ATF)', ch: '27' },
  { code: '271042', desc: 'High speed diesel (HSD)', ch: '27' },
  { code: '271049', desc: 'Other gas oils', ch: '27' },
  { code: '271091', desc: 'Waste oils', ch: '27' },
  { code: '2711', desc: 'Petroleum gases and other gaseous hydrocarbons (LPG, CNG)', ch: '27' },
  { code: '271111', desc: 'Natural gas, liquefied', ch: '27' },
  { code: '271112', desc: 'Propane, liquefied', ch: '27' },
  { code: '271113', desc: 'Butanes, liquefied (LPG)', ch: '27' },
  { code: '271121', desc: 'Natural gas in gaseous state (CNG)', ch: '27' },
  { code: '2712', desc: 'Petroleum jelly; paraffin wax; petroleum waxes', ch: '27' },
  { code: '2714', desc: 'Bitumen and asphalt, natural', ch: '27' },

  // ── Chapter 28: Inorganic chemicals ───────────────────────────────────────
  { code: '2801', desc: 'Fluorine, chlorine, bromine and iodine', ch: '28' },
  { code: '2804', desc: 'Hydrogen, rare gases and other non-metals (oxygen, nitrogen)', ch: '28' },
  { code: '2806', desc: 'Hydrogen chloride; chlorosulphuric acid', ch: '28' },
  { code: '2807', desc: 'Sulphuric acid; oleum', ch: '28' },
  { code: '2808', desc: 'Nitric acid; sulphonitric acids', ch: '28' },
  { code: '2814', desc: 'Ammonia, anhydrous or in aqueous solution', ch: '28' },
  { code: '2815', desc: 'Sodium hydroxide (caustic soda); potassium hydroxide (caustic potash)', ch: '28' },
  { code: '2823', desc: 'Titanium oxides', ch: '28' },
  { code: '2836', desc: 'Carbonates; peroxocarbonates; soda ash', ch: '28' },
  { code: '2849', desc: 'Carbides', ch: '28' },

  // ── Chapter 29: Organic chemicals ─────────────────────────────────────────
  { code: '2901', desc: 'Acyclic hydrocarbons (ethylene, propylene, butylene)', ch: '29' },
  { code: '2902', desc: 'Cyclic hydrocarbons (benzene, toluene, xylene)', ch: '29' },
  { code: '2905', desc: 'Acyclic alcohols and their halogenated derivatives (methanol, ethanol)', ch: '29' },
  { code: '2906', desc: 'Cyclic alcohols and their halogenated derivatives', ch: '29' },
  { code: '2915', desc: 'Saturated acyclic monocarboxylic acids (acetic acid, formic acid)', ch: '29' },
  { code: '2916', desc: 'Unsaturated acyclic monocarboxylic acids; cyclic monocarboxylic acids', ch: '29' },
  { code: '2921', desc: 'Amine-function compounds', ch: '29' },
  { code: '2922', desc: 'Oxygen-function amino compounds', ch: '29' },
  { code: '2933', desc: 'Heterocyclic compounds with nitrogen heteroatoms (pyridine, etc.)', ch: '29' },
  { code: '2934', desc: 'Nucleic acids and their salts; heterocyclic compounds', ch: '29' },

  // ── Chapter 30: Pharmaceutical products ───────────────────────────────────
  { code: '3001', desc: 'Glands and other organs for organo-therapeutic uses; dried', ch: '30' },
  { code: '3002', desc: 'Human blood; animal blood; vaccines, toxins, cultures of micro-organisms', ch: '30' },
  { code: '300215', desc: 'COVID-19 vaccines and similar immunological products', ch: '30' },
  { code: '3003', desc: 'Medicaments in bulk (mixed or unmixed, not in measured doses)', ch: '30' },
  { code: '3004', desc: 'Medicaments in measured doses (tablets, capsules, injections, patches)', ch: '30' },
  { code: '300410', desc: 'Containing penicillins or streptomycins', ch: '30' },
  { code: '300420', desc: 'Containing antibiotics (other than penicillins/streptomycins)', ch: '30' },
  { code: '300431', desc: 'Containing insulin', ch: '30' },
  { code: '300440', desc: 'Containing alkaloids but no antibiotics or hormones', ch: '30' },
  { code: '300450', desc: 'Other medicaments containing vitamins or provitamins', ch: '30' },
  { code: '300490', desc: 'Other medicaments (NOS)', ch: '30' },
  { code: '3005', desc: 'Wadding, gauze, bandages and similar articles for medical use', ch: '30' },
  { code: '3006', desc: 'Pharmaceutical goods (sterile surgical catgut, bone cements, etc.)', ch: '30' },

  // ── Chapter 31: Fertilisers ───────────────────────────────────────────────
  { code: '3101', desc: 'Animal or vegetable fertilisers; mixtures thereof', ch: '31' },
  { code: '3102', desc: 'Mineral or chemical fertilisers, nitrogenous (urea, ammonium nitrate)', ch: '31' },
  { code: '310210', desc: 'Urea', ch: '31' },
  { code: '310221', desc: 'Ammonium sulphate', ch: '31' },
  { code: '3103', desc: 'Mineral or chemical fertilisers, phosphatic (superphosphate)', ch: '31' },
  { code: '3104', desc: 'Mineral or chemical fertilisers, potassic (potassium chloride)', ch: '31' },
  { code: '3105', desc: 'Mineral or chemical fertilisers containing NPK', ch: '31' },

  // ── Chapter 33: Cosmetics ─────────────────────────────────────────────────
  { code: '3301', desc: 'Essential oils (whether or not terpeneless)', ch: '33' },
  { code: '3302', desc: 'Mixtures of odoriferous substances; perfumery raw materials', ch: '33' },
  { code: '3303', desc: 'Perfumes and toilet waters', ch: '33' },
  { code: '3304', desc: 'Beauty or make-up preparations; skin-care preparations', ch: '33' },
  { code: '330410', desc: 'Lip make-up preparations', ch: '33' },
  { code: '330420', desc: 'Eye make-up preparations', ch: '33' },
  { code: '330430', desc: 'Manicure or pedicure preparations', ch: '33' },
  { code: '330491', desc: 'Powders, whether or not compressed', ch: '33' },
  { code: '330499', desc: 'Other beauty / make-up / skin-care preparations', ch: '33' },
  { code: '3305', desc: 'Preparations for use on the hair (shampoos, conditioners)', ch: '33' },
  { code: '3306', desc: 'Preparations for oral or dental hygiene (toothpaste)', ch: '33' },
  { code: '3307', desc: 'Pre-shave, shaving or after-shave preparations; deodorants', ch: '33' },

  // ── Chapter 34: Soap and detergents ───────────────────────────────────────
  { code: '3401', desc: 'Soap; organic surface-active products for use as soap', ch: '34' },
  { code: '3402', desc: 'Washing preparations, cleaning preparations, lubricating preparations', ch: '34' },
  { code: '3403', desc: 'Lubricating preparations (cutting oil fluids, rust/corrosion inhibitors)', ch: '34' },
  { code: '3405', desc: 'Polishes and creams for footwear, furniture, floors, coachwork', ch: '34' },
  { code: '3406', desc: 'Candles, tapers and the like', ch: '34' },

  // ── Chapter 38: Chemical products ─────────────────────────────────────────
  { code: '3801', desc: 'Artificial graphite; colloidal or semi-colloidal graphite', ch: '38' },
  { code: '3804', desc: 'Residual lyes from manufacture of wood pulp (lignin sulphonates)', ch: '38' },
  { code: '3808', desc: 'Insecticides, rodenticides, fungicides, herbicides, disinfectants', ch: '38' },
  { code: '3809', desc: 'Finishing agents, dye carriers for dyeing and printing; sizing agents', ch: '38' },
  { code: '3814', desc: 'Organic composite solvents and thinners (paint thinners)', ch: '38' },
  { code: '3819', desc: 'Hydraulic brake fluids and other prepared liquids for hydraulic transmission', ch: '38' },
  { code: '3820', desc: 'Anti-freezing preparations and prepared de-icing fluids', ch: '38' },
  { code: '3824', desc: 'Prepared binders for foundry moulds; chemical products NES', ch: '38' },

  // ── Chapter 39: Plastics ───────────────────────────────────────────────────
  { code: '3901', desc: 'Polymers of ethylene, in primary forms (HDPE, LDPE, LLDPE)', ch: '39' },
  { code: '390110', desc: 'Polyethylene having a specific gravity <0.94 (LDPE)', ch: '39' },
  { code: '390120', desc: 'Polyethylene having a specific gravity ≥0.94 (HDPE)', ch: '39' },
  { code: '3902', desc: 'Polymers of propylene or of other olefins, in primary forms (PP)', ch: '39' },
  { code: '390210', desc: 'Polypropylene', ch: '39' },
  { code: '3903', desc: 'Polymers of styrene (PS, ABS, SAN) in primary forms', ch: '39' },
  { code: '3904', desc: 'Polymers of vinyl chloride (PVC) in primary forms', ch: '39' },
  { code: '390410', desc: 'PVC, not mixed with any other substance', ch: '39' },
  { code: '390421', desc: 'PVC, non-plasticised', ch: '39' },
  { code: '390422', desc: 'PVC, plasticised', ch: '39' },
  { code: '3905', desc: 'Polymers of vinyl acetate or other vinyl esters; polyvinyl alcohol (PVA)', ch: '39' },
  { code: '3906', desc: 'Acrylic polymers in primary forms (PMMA, polyacrylate)', ch: '39' },
  { code: '3907', desc: 'Polyacetals, polycarbonates, epoxide resins (PC, Epoxy)', ch: '39' },
  { code: '390720', desc: 'Polyethylene terephthalate (PET)', ch: '39' },
  { code: '390730', desc: 'Epoxide resins', ch: '39' },
  { code: '3908', desc: 'Polyamides (Nylon) in primary forms', ch: '39' },
  { code: '3909', desc: 'Amino-resins; phenolic resins; polyurethanes in primary forms', ch: '39' },
  { code: '3915', desc: 'Waste, parings and scrap of plastics', ch: '39' },
  { code: '3916', desc: 'Monofilament of plastics; rods, sticks and profile shapes', ch: '39' },
  { code: '3917', desc: 'Tubes, pipes and hoses, and fittings therefor, of plastics', ch: '39' },
  { code: '3919', desc: 'Self-adhesive plates, sheets, film, foil, tape, strip of plastics', ch: '39' },
  { code: '3920', desc: 'Other plates, sheets, film, foil and strip of plastics', ch: '39' },
  { code: '3923', desc: 'Articles for the conveyance or packing of goods of plastics', ch: '39' },
  { code: '3924', desc: 'Tableware, kitchenware, household articles of plastics', ch: '39' },
  { code: '3926', desc: 'Other articles of plastics (office/school supplies, fittings)', ch: '39' },

  // ── Chapter 40: Rubber ────────────────────────────────────────────────────
  { code: '4001', desc: 'Natural rubber, balata, gutta-percha in primary forms or plates', ch: '40' },
  { code: '4002', desc: 'Synthetic rubber and factice derived from oils', ch: '40' },
  { code: '4005', desc: 'Compounded rubber, unvulcanised, in primary forms or plates', ch: '40' },
  { code: '4007', desc: 'Vulcanised rubber thread and cord', ch: '40' },
  { code: '4008', desc: 'Plates, sheets, strip, rods and profile shapes, of vulcanised rubber', ch: '40' },
  { code: '4009', desc: 'Tubes, pipes and hoses of vulcanised rubber', ch: '40' },
  { code: '4011', desc: 'New pneumatic tyres, of rubber', ch: '40' },
  { code: '401110', desc: 'New pneumatic tyres — motor cars (including station wagons)', ch: '40' },
  { code: '401120', desc: 'New pneumatic tyres — buses or lorries', ch: '40' },
  { code: '401140', desc: 'New pneumatic tyres — motorcycles', ch: '40' },
  { code: '4012', desc: 'Retreaded or used pneumatic tyres of rubber', ch: '40' },
  { code: '4013', desc: 'Inner tubes, of rubber', ch: '40' },
  { code: '4016', desc: 'Other articles of vulcanised rubber (gaskets, seals, mats)', ch: '40' },

  // ── Chapter 44: Wood ──────────────────────────────────────────────────────
  { code: '4401', desc: 'Fuel wood; wood chips; sawdust, wood waste and scrap', ch: '44' },
  { code: '4403', desc: 'Wood in the rough (logs), whether or not stripped', ch: '44' },
  { code: '4407', desc: 'Wood sawn or chipped lengthwise, sliced or peeled (planks, boards, beams)', ch: '44' },
  { code: '4408', desc: 'Sheets for veneering; plywood; other wood sawn to a thickness ≤6mm', ch: '44' },
  { code: '4409', desc: 'Wood continuously shaped (tongued, grooved, moulded, rounded)', ch: '44' },
  { code: '4410', desc: 'Particle board, oriented strand board (OSB) and similar board of wood', ch: '44' },
  { code: '4411', desc: 'Medium density fibreboard (MDF) and fibreboard of wood', ch: '44' },
  { code: '4412', desc: 'Plywood, veneered panels and similar laminated wood', ch: '44' },
  { code: '4418', desc: 'Builders\' joinery and carpentry (doors, windows, flooring)', ch: '44' },

  // ── Chapter 48: Paper ─────────────────────────────────────────────────────
  { code: '4801', desc: 'Newsprint, in rolls or sheets', ch: '48' },
  { code: '4802', desc: 'Uncoated paper and paperboard for writing, printing (copier paper)', ch: '48' },
  { code: '4804', desc: 'Uncoated kraft paper and paperboard, in rolls or sheets', ch: '48' },
  { code: '4805', desc: 'Other uncoated paper and paperboard (fluting medium, testliner)', ch: '48' },
  { code: '4807', desc: 'Composite paper and paperboard', ch: '48' },
  { code: '4808', desc: 'Corrugated paper and paperboard; creped, crinkled, embossed', ch: '48' },
  { code: '4810', desc: 'Paper and paperboard, coated on one or both sides with kaolin', ch: '48' },
  { code: '4811', desc: 'Paper, paperboard, coated, impregnated or covered with plastics', ch: '48' },
  { code: '4818', desc: 'Toilet paper, handkerchiefs, facial tissues, tissue paper', ch: '48' },
  { code: '4819', desc: 'Cartons, boxes, cases, bags and other packing containers of paper', ch: '48' },
  { code: '4820', desc: 'Registers, account books, notebooks, diaries of paper', ch: '48' },
  { code: '4821', desc: 'Paper or paperboard labels of all kinds, printed or not', ch: '48' },
  { code: '4823', desc: 'Other paper, paperboard, cellulose wadding; cups, plates, trays', ch: '48' },

  // ── Chapter 52: Cotton ────────────────────────────────────────────────────
  { code: '5201', desc: 'Cotton, not carded or combed', ch: '52' },
  { code: '520100', desc: 'Cotton, not carded or combed', ch: '52' },
  { code: '5203', desc: 'Cotton, carded or combed', ch: '52' },
  { code: '5205', desc: 'Cotton yarn (other than sewing thread) ≥85% cotton, not retail', ch: '52' },
  { code: '520511', desc: 'Single yarn, uncombed fibres, 714.29 dtex or more (14 Nm)', ch: '52' },
  { code: '520512', desc: 'Single yarn, uncombed fibres, 232.56–714.29 dtex', ch: '52' },
  { code: '520513', desc: 'Single yarn, uncombed fibres, 192.31–232.56 dtex', ch: '52' },
  { code: '5206', desc: 'Cotton yarn (other than sewing thread) <85% cotton, not retail', ch: '52' },
  { code: '5207', desc: 'Cotton yarn (other than sewing thread), put up for retail sale', ch: '52' },
  { code: '5208', desc: 'Woven fabrics of cotton, ≥85% cotton, ≤200 g/m²', ch: '52' },
  { code: '520811', desc: 'Woven, plain weave, ≤100 g/m², unbleached', ch: '52' },
  { code: '520812', desc: 'Woven, plain weave, >100 g/m², unbleached', ch: '52' },
  { code: '520821', desc: 'Woven, plain weave, ≤100 g/m², bleached', ch: '52' },
  { code: '520831', desc: 'Woven, plain weave, ≤100 g/m², dyed', ch: '52' },
  { code: '520841', desc: 'Woven, plain weave, ≤100 g/m², yarn-dyed', ch: '52' },
  { code: '520851', desc: 'Woven, plain weave, ≤100 g/m², printed', ch: '52' },
  { code: '5209', desc: 'Woven fabrics of cotton, ≥85% cotton, >200 g/m²', ch: '52' },
  { code: '5210', desc: 'Woven fabrics of cotton, <85% cotton, ≤200 g/m², mixed with man-made fibres', ch: '52' },

  // ── Chapter 54: Man-made filaments ────────────────────────────────────────
  { code: '5401', desc: 'Sewing thread of man-made filaments', ch: '54' },
  { code: '5402', desc: 'High tenacity yarn of nylon, polyesters or viscose', ch: '54' },
  { code: '5403', desc: 'High tenacity yarn of viscose rayon, etc.', ch: '54' },
  { code: '5407', desc: 'Woven fabrics of synthetic filament yarn (polyester, nylon)', ch: '54' },
  { code: '5408', desc: 'Woven fabrics of artificial filament yarn (viscose, modal)', ch: '54' },

  // ── Chapter 55: Man-made staple fibres ────────────────────────────────────
  { code: '5501', desc: 'Synthetic filament tow (polyester, nylon, acrylic)', ch: '55' },
  { code: '5503', desc: 'Synthetic staple fibres, not carded or combed (polyester, nylon)', ch: '55' },
  { code: '5504', desc: 'Artificial staple fibres, not carded or combed (viscose, modal)', ch: '55' },
  { code: '5509', desc: 'Yarn of synthetic staple fibres (other than sewing thread)', ch: '55' },
  { code: '5512', desc: 'Woven fabrics of synthetic staple fibres ≥85%', ch: '55' },
  { code: '5513', desc: 'Woven fabrics of synthetic staple fibres <85%, mixed with cotton', ch: '55' },

  // ── Chapter 61: Knitted apparel ───────────────────────────────────────────
  { code: '6101', desc: 'Men\'s overcoats, car-coats, cloaks, anoraks — knitted or crocheted', ch: '61' },
  { code: '6102', desc: 'Women\'s overcoats, car-coats, cloaks, anoraks — knitted or crocheted', ch: '61' },
  { code: '6103', desc: 'Men\'s suits, ensembles, jackets, blazers, trousers — knitted', ch: '61' },
  { code: '6104', desc: 'Women\'s suits, ensembles, jackets, blazers, dresses — knitted', ch: '61' },
  { code: '6105', desc: 'Men\'s shirts, knitted or crocheted', ch: '61' },
  { code: '6106', desc: 'Women\'s blouses and shirts, knitted or crocheted', ch: '61' },
  { code: '6109', desc: 'T-shirts, singlets and other vests, knitted or crocheted', ch: '61' },
  { code: '610910', desc: 'T-shirts, singlets and other vests of cotton, knitted', ch: '61' },
  { code: '610990', desc: 'T-shirts, singlets of other textile materials, knitted', ch: '61' },
  { code: '6110', desc: 'Jerseys, pullovers, sweatshirts, waistcoats and similar articles, knitted', ch: '61' },
  { code: '6111', desc: 'Babies\' garments and clothing accessories, knitted or crocheted', ch: '61' },
  { code: '6115', desc: 'Pantyhose, tights, stockings, socks and other hosiery', ch: '61' },
  { code: '6116', desc: 'Gloves, mittens and mitts, knitted or crocheted', ch: '61' },

  // ── Chapter 62: Woven apparel ─────────────────────────────────────────────
  { code: '6201', desc: 'Men\'s overcoats, car-coats, cloaks, anoraks — not knitted', ch: '62' },
  { code: '6202', desc: 'Women\'s overcoats, car-coats, cloaks, anoraks — not knitted', ch: '62' },
  { code: '6203', desc: 'Men\'s suits, ensembles, jackets, blazers, trousers — not knitted', ch: '62' },
  { code: '620311', desc: 'Men\'s suits of wool or fine animal hair', ch: '62' },
  { code: '620312', desc: 'Men\'s suits of synthetic fibres', ch: '62' },
  { code: '620319', desc: 'Men\'s suits of other textile materials', ch: '62' },
  { code: '620341', desc: 'Men\'s trousers of wool or fine animal hair', ch: '62' },
  { code: '620342', desc: 'Men\'s trousers of cotton (jeans, trousers)', ch: '62' },
  { code: '620343', desc: 'Men\'s trousers of synthetic fibres', ch: '62' },
  { code: '6204', desc: 'Women\'s suits, ensembles, jackets, dresses, skirts — not knitted', ch: '62' },
  { code: '6205', desc: 'Men\'s shirts — not knitted', ch: '62' },
  { code: '6206', desc: 'Women\'s blouses and shirts — not knitted', ch: '62' },
  { code: '6207', desc: 'Men\'s singlets, underpants, briefs, pyjamas, dressing gowns', ch: '62' },
  { code: '6208', desc: 'Women\'s singlets, slips, petticoats, briefs, nightdresses', ch: '62' },
  { code: '6211', desc: 'Tracksuits, ski suits, swimwear and other garments', ch: '62' },
  { code: '6214', desc: 'Shawls, scarves, mufflers, mantillas, veils and the like', ch: '62' },

  // ── Chapter 63: Other textile articles ────────────────────────────────────
  { code: '6301', desc: 'Blankets and travelling rugs', ch: '63' },
  { code: '6302', desc: 'Bed linen, table linen, toilet linen and kitchen linen', ch: '63' },
  { code: '6303', desc: 'Curtains (including drapes) and interior blinds; curtain or bed valances', ch: '63' },
  { code: '6304', desc: 'Bedspreads; other furnishing articles (cushions, pillow covers)', ch: '63' },
  { code: '6305', desc: 'Sacks and bags for packing of goods (jute, cotton, polypropylene)', ch: '63' },
  { code: '6306', desc: 'Tarpaulins, awnings, sunblinds, tents; sails; camping goods', ch: '63' },
  { code: '6307', desc: 'Other made-up articles (cleaning cloths, life jackets, flags, face masks)', ch: '63' },

  // ── Chapter 64: Footwear ──────────────────────────────────────────────────
  { code: '6401', desc: 'Waterproof footwear with outer soles and uppers of rubber or plastics', ch: '64' },
  { code: '6402', desc: 'Other footwear with outer soles and uppers of rubber or plastics', ch: '64' },
  { code: '640211', desc: 'Ski-boots, cross-country ski footwear and snowboard boots', ch: '64' },
  { code: '640219', desc: 'Sports footwear of rubber or plastics', ch: '64' },
  { code: '640291', desc: 'Other footwear of rubber or plastics covering the ankle', ch: '64' },
  { code: '640299', desc: 'Other footwear of rubber or plastics (sandals, slippers)', ch: '64' },
  { code: '6403', desc: 'Footwear with outer soles of rubber, plastics, leather — uppers of leather', ch: '64' },
  { code: '640311', desc: 'Ski-boots and snowboard boots with leather uppers', ch: '64' },
  { code: '640391', desc: 'Footwear with leather uppers covering the ankle', ch: '64' },
  { code: '640399', desc: 'Other footwear with leather uppers (shoes, oxfords)', ch: '64' },
  { code: '6404', desc: 'Footwear with outer soles of rubber or plastics and uppers of textile', ch: '64' },
  { code: '6405', desc: 'Other footwear (canvas shoes, jute footwear)', ch: '64' },

  // ── Chapter 69: Ceramics ───────────────────────────────────────────────────
  { code: '6901', desc: 'Bricks, blocks, tiles and other ceramic goods for construction', ch: '69' },
  { code: '6902', desc: 'Refractory bricks, blocks, tiles and similar refractory ceramic goods', ch: '69' },
  { code: '6904', desc: 'Ceramic building bricks, flooring blocks, support or filler tiles', ch: '69' },
  { code: '6905', desc: 'Roofing tiles, chimney-pots, cowls, chimney liners of ceramic', ch: '69' },
  { code: '6907', desc: 'Ceramic flags and paving, hearth or wall tiles (vitrified tiles)', ch: '69' },
  { code: '6910', desc: 'Ceramic sinks, wash basins, baths, bidets, WC pans — sanitary ware', ch: '69' },
  { code: '6911', desc: 'Tableware, kitchenware, household articles of porcelain/china', ch: '69' },
  { code: '6912', desc: 'Ceramic tableware, kitchenware (other than porcelain)', ch: '69' },

  // ── Chapter 70: Glass ─────────────────────────────────────────────────────
  { code: '7003', desc: 'Cast glass and rolled glass, in sheets or profiles (not wired)', ch: '70' },
  { code: '7004', desc: 'Drawn glass and blown glass, in sheets', ch: '70' },
  { code: '7005', desc: 'Float glass and surface ground or polished glass, in sheets', ch: '70' },
  { code: '7007', desc: 'Safety glass (toughened / tempered; laminated)', ch: '70' },
  { code: '7008', desc: 'Multiple-walled insulating units of glass (double glazing)', ch: '70' },
  { code: '7009', desc: 'Glass mirrors, whether or not framed', ch: '70' },
  { code: '7010', desc: 'Carboys, bottles, flasks, jars, pots, ampoules of glass', ch: '70' },
  { code: '7013', desc: 'Glassware for table, kitchen, toilet, office, indoor decoration', ch: '70' },
  { code: '7017', desc: 'Laboratory, hygienic or pharmaceutical glassware', ch: '70' },

  // ── Chapter 71: Jewellery / precious metals ───────────────────────────────
  { code: '7101', desc: 'Pearls, natural or cultured', ch: '71' },
  { code: '7102', desc: 'Diamonds, whether or not worked', ch: '71' },
  { code: '710210', desc: 'Unsorted diamonds', ch: '71' },
  { code: '710221', desc: 'Industrial diamonds, unworked or simply sawn', ch: '71' },
  { code: '710231', desc: 'Non-industrial diamonds, unworked or simply sawn', ch: '71' },
  { code: '7103', desc: 'Precious stones (other than diamonds) and semi-precious stones', ch: '71' },
  { code: '7106', desc: 'Silver (including silver plated with gold or platinum)', ch: '71' },
  { code: '710611', desc: 'Silver powder', ch: '71' },
  { code: '710691', desc: 'Unwrought silver', ch: '71' },
  { code: '7108', desc: 'Gold (including gold plated with platinum)', ch: '71' },
  { code: '710811', desc: 'Gold powder', ch: '71' },
  { code: '710812', desc: 'Unwrought gold (bars, ingots)', ch: '71' },
  { code: '710820', desc: 'Monetary gold', ch: '71' },
  { code: '7113', desc: 'Articles of jewellery and parts thereof of precious metal', ch: '71' },
  { code: '711311', desc: 'Jewellery of silver', ch: '71' },
  { code: '711319', desc: 'Jewellery of other precious metals (gold, platinum)', ch: '71' },
  { code: '7114', desc: 'Articles of goldsmiths\' or silversmiths\' wares and parts thereof', ch: '71' },
  { code: '7117', desc: 'Imitation jewellery (fashion jewellery)', ch: '71' },

  // ── Chapter 72: Iron and steel ────────────────────────────────────────────
  { code: '7201', desc: 'Pig iron and spiegeleisen in pigs, blocks or other primary forms', ch: '72' },
  { code: '7204', desc: 'Ferrous waste and scrap; remelting scrap ingots of iron or steel', ch: '72' },
  { code: '7206', desc: 'Iron and non-alloy steel in ingots or other primary forms', ch: '72' },
  { code: '7207', desc: 'Semi-finished products of iron or non-alloy steel (billets, blooms)', ch: '72' },
  { code: '7208', desc: 'Flat-rolled products of iron or non-alloy steel, ≥600mm wide, hot-rolled', ch: '72' },
  { code: '7209', desc: 'Flat-rolled products of iron or non-alloy steel, ≥600mm wide, cold-rolled', ch: '72' },
  { code: '7210', desc: 'Flat-rolled products coated with tin, lead, chromium, zinc (GI sheets)', ch: '72' },
  { code: '721011', desc: 'Tinplate (electrolytically plated)', ch: '72' },
  { code: '721030', desc: 'Electrolytically plated or coated with zinc (galvanised)', ch: '72' },
  { code: '721061', desc: 'Flat-rolled, coated with aluminium zinc alloy (Galvalume)', ch: '72' },
  { code: '7213', desc: 'Bars and rods, hot-rolled, in irregularly wound coils (wire rods)', ch: '72' },
  { code: '7214', desc: 'Other bars and rods of iron or non-alloy steel (TMT bars, rounds)', ch: '72' },
  { code: '721410', desc: 'Forged bars and rods', ch: '72' },
  { code: '721420', desc: 'Bars and rods, containing indentations, ribs, grooves or other deformations (TMT/HYSD)', ch: '72' },
  { code: '7216', desc: 'Angles, shapes and sections of iron or non-alloy steel (I-beams, channels)', ch: '72' },
  { code: '7217', desc: 'Wire of iron or non-alloy steel', ch: '72' },
  { code: '7219', desc: 'Flat-rolled products of stainless steel, ≥600mm wide', ch: '72' },
  { code: '7222', desc: 'Other bars and rods of stainless steel; angles, shapes and sections', ch: '72' },
  { code: '7225', desc: 'Flat-rolled products of other alloy steel, ≥600mm wide', ch: '72' },
  { code: '7228', desc: 'Other bars and rods of other alloy steel; hollow drill bars and rods', ch: '72' },

  // ── Chapter 73: Articles of iron or steel ─────────────────────────────────
  { code: '7301', desc: 'Sheet piling of iron or steel; welded angles, shapes and sections', ch: '73' },
  { code: '7302', desc: 'Railway track construction material (rails, sleepers, fish plates)', ch: '73' },
  { code: '7304', desc: 'Tubes, pipes and hollow profiles, seamless, of iron or steel', ch: '73' },
  { code: '7305', desc: 'Other tubes and pipes (large diameter, welded) of iron or steel', ch: '73' },
  { code: '7306', desc: 'Other tubes, pipes and hollow profiles of iron or steel (ERW pipes)', ch: '73' },
  { code: '7307', desc: 'Tube or pipe fittings of iron or steel (couplings, elbows, flanges)', ch: '73' },
  { code: '7308', desc: 'Structures (bridges, towers, columns) and parts thereof of iron or steel', ch: '73' },
  { code: '7309', desc: 'Reservoirs, tanks, vats and similar containers (>300 litres) of iron or steel', ch: '73' },
  { code: '7310', desc: 'Tanks, casks, drums, cans, boxes of iron or steel (≤300 litres)', ch: '73' },
  { code: '7312', desc: 'Stranded wire, ropes, cables, plaited bands of iron or steel', ch: '73' },
  { code: '7313', desc: 'Barbed wire of iron or steel; fencing of iron or steel wire', ch: '73' },
  { code: '7315', desc: 'Chain and parts thereof, of iron or steel', ch: '73' },
  { code: '7317', desc: 'Nails, tacks, drawing pins, staples of iron or steel', ch: '73' },
  { code: '7318', desc: 'Screws, bolts, nuts, washers of iron or steel', ch: '73' },
  { code: '7320', desc: 'Springs of iron or steel (coil springs, leaf springs)', ch: '73' },
  { code: '7323', desc: 'Table, kitchen, household articles of iron or steel (utensils)', ch: '73' },
  { code: '7326', desc: 'Other articles of iron or steel (forgings, stampings)', ch: '73' },

  // ── Chapter 74: Copper ────────────────────────────────────────────────────
  { code: '7401', desc: 'Copper mattes; cement copper (precipitate copper)', ch: '74' },
  { code: '7403', desc: 'Refined copper and copper alloys, unwrought', ch: '74' },
  { code: '740311', desc: 'Cathodes and sections of cathodes (refined copper)', ch: '74' },
  { code: '7407', desc: 'Copper bars, rods and profiles', ch: '74' },
  { code: '7408', desc: 'Copper wire', ch: '74' },
  { code: '7409', desc: 'Copper plates, sheets and strip (>0.15mm thick)', ch: '74' },
  { code: '7411', desc: 'Copper tubes and pipes', ch: '74' },
  { code: '7412', desc: 'Copper tube or pipe fittings', ch: '74' },
  { code: '7413', desc: 'Stranded wire, cables, plaited bands of copper', ch: '74' },
  { code: '7418', desc: 'Table, kitchen, household articles of copper', ch: '74' },

  // ── Chapter 76: Aluminium ─────────────────────────────────────────────────
  { code: '7601', desc: 'Unwrought aluminium', ch: '76' },
  { code: '760110', desc: 'Aluminium, not alloyed, unwrought', ch: '76' },
  { code: '760120', desc: 'Aluminium alloys, unwrought', ch: '76' },
  { code: '7604', desc: 'Aluminium bars, rods and profiles', ch: '76' },
  { code: '7605', desc: 'Aluminium wire', ch: '76' },
  { code: '7606', desc: 'Aluminium plates, sheets and strip (>0.2mm thick)', ch: '76' },
  { code: '7607', desc: 'Aluminium foil (≤0.2mm thick)', ch: '76' },
  { code: '7608', desc: 'Aluminium tubes and pipes', ch: '76' },
  { code: '7610', desc: 'Aluminium structures and parts thereof (doors, windows, curtain walls)', ch: '76' },
  { code: '7612', desc: 'Aluminium casks, drums, cans, boxes for packing', ch: '76' },
  { code: '7613', desc: 'Aluminium containers for compressed or liquefied gas', ch: '76' },
  { code: '7616', desc: 'Other articles of aluminium (castings, forgings, stampings)', ch: '76' },

  // ── Chapter 84: Machinery ─────────────────────────────────────────────────
  { code: '8401', desc: 'Nuclear reactors; fuel elements; isotope separation machinery', ch: '84' },
  { code: '8402', desc: 'Steam or other vapour generating boilers (steam boilers)', ch: '84' },
  { code: '8404', desc: 'Auxiliary plant for use with boilers (economisers, condensers)', ch: '84' },
  { code: '8405', desc: 'Producer gas or water gas generators; acetylene gas generators', ch: '84' },
  { code: '8406', desc: 'Steam turbines and other vapour turbines', ch: '84' },
  { code: '8407', desc: 'Spark-ignition reciprocating or rotary internal combustion engines', ch: '84' },
  { code: '8408', desc: 'Compression-ignition internal combustion piston engines (diesel engines)', ch: '84' },
  { code: '8409', desc: 'Parts for internal combustion engines (pistons, cylinder liners)', ch: '84' },
  { code: '8410', desc: 'Hydraulic turbines, water wheels and regulators', ch: '84' },
  { code: '8411', desc: 'Turbojets, turbo-propellers and other gas turbines (aircraft engines)', ch: '84' },
  { code: '8412', desc: 'Other engines and motors (hydraulic, pneumatic, jet propulsion)', ch: '84' },
  { code: '8413', desc: 'Pumps for liquids (centrifugal, submersible, gear, screw pumps)', ch: '84' },
  { code: '841311', desc: 'Dispensing pumps for fuelling stations', ch: '84' },
  { code: '841319', desc: 'Other pumps fitted with measuring devices', ch: '84' },
  { code: '841370', desc: 'Other centrifugal pumps', ch: '84' },
  { code: '8414', desc: 'Air or vacuum pumps; compressors; fans; hoods', ch: '84' },
  { code: '841430', desc: 'Compressors used in refrigerating equipment', ch: '84' },
  { code: '841451', desc: 'Table, floor, wall, window, ceiling or roof fans with motor ≤125W', ch: '84' },
  { code: '841459', desc: 'Other fans', ch: '84' },
  { code: '841480', desc: 'Air compressors (reciprocating, screw, centrifugal)', ch: '84' },
  { code: '8415', desc: 'Air conditioning machines, incorporating a refrigerating unit (AC)', ch: '84' },
  { code: '841510', desc: 'Window or wall type air conditioners, self-contained (split AC)', ch: '84' },
  { code: '841581', desc: 'Incorporating a refrigerating unit — other AC', ch: '84' },
  { code: '8416', desc: 'Furnace burners for liquid fuel, gas or pulverised solid fuel', ch: '84' },
  { code: '8417', desc: 'Industrial or laboratory furnaces and ovens (non-electric)', ch: '84' },
  { code: '8418', desc: 'Refrigerators, freezers, heat pumps, cooling equipment', ch: '84' },
  { code: '841810', desc: 'Combined refrigerator-freezers with separate external doors', ch: '84' },
  { code: '841821', desc: 'Household type compression refrigerators', ch: '84' },
  { code: '841830', desc: 'Freezers of chest type, not exceeding 800 litres', ch: '84' },
  { code: '841840', desc: 'Freezers of upright type, not exceeding 900 litres', ch: '84' },
  { code: '8419', desc: 'Machinery for heat-treating materials (pasteurising, dryers, distillation plant)', ch: '84' },
  { code: '8421', desc: 'Centrifuges; filtering or purifying machinery for liquids or gases', ch: '84' },
  { code: '8422', desc: 'Dish-washing machines; machinery for cleaning and filling bottles', ch: '84' },
  { code: '8423', desc: 'Weighing machinery (scales, balances); weight pieces', ch: '84' },
  { code: '8424', desc: 'Mechanical appliances for projecting, dispersing or spraying (fire extinguishers, spray guns)', ch: '84' },
  { code: '8425', desc: 'Pulley tackle and hoists; winches; jacks', ch: '84' },
  { code: '8426', desc: 'Ships\' derricks; cranes; mobile lifting frames (tower cranes, gantry cranes)', ch: '84' },
  { code: '8427', desc: 'Fork-lift trucks; other works trucks fitted with lifting equipment', ch: '84' },
  { code: '8428', desc: 'Other lifting, handling, loading or unloading machinery (conveyors, escalators)', ch: '84' },
  { code: '8429', desc: 'Self-propelled bulldozers, excavators, shovel-loaders, road rollers', ch: '84' },
  { code: '8430', desc: 'Other moving, grading, levelling, boring, extracting machinery (mining)', ch: '84' },
  { code: '8431', desc: 'Parts suitable for use with machinery of headings 8425 to 8430', ch: '84' },
  { code: '8432', desc: 'Agricultural, horticultural or forestry machinery (tractors excluded)', ch: '84' },
  { code: '8433', desc: 'Harvesting or threshing machinery; combine harvesters', ch: '84' },
  { code: '8434', desc: 'Milking machines and dairy machinery', ch: '84' },
  { code: '8435', desc: 'Presses, crushers and similar machinery for wine, fruit juice', ch: '84' },
  { code: '8436', desc: 'Other agricultural, horticultural and forestry machinery', ch: '84' },
  { code: '8437', desc: 'Machines for cleaning, sorting grain; milling machinery for cereals', ch: '84' },
  { code: '8438', desc: 'Machinery for the industrial preparation of food or drink', ch: '84' },
  { code: '8439', desc: 'Machinery for making pulp of fibrous cellulosic material; paper machines', ch: '84' },
  { code: '8440', desc: 'Book-binding machinery including book-sewing machines', ch: '84' },
  { code: '8441', desc: 'Other machinery for making up paper pulp, paper or paperboard', ch: '84' },
  { code: '8443', desc: 'Printing machinery; machines for uses ancillary to printing (offset printing)', ch: '84' },
  { code: '8450', desc: 'Household or laundry-type washing machines (washing machine)', ch: '84' },
  { code: '845011', desc: 'Fully automatic washing machines, ≤10 kg dry linen capacity', ch: '84' },
  { code: '845012', desc: 'Other machines with built-in centrifugal drier, ≤10 kg', ch: '84' },
  { code: '8451', desc: 'Machinery for washing, cleaning, drying, ironing, pressing textile', ch: '84' },
  { code: '8452', desc: 'Sewing machines (industrial and household)', ch: '84' },
  { code: '8453', desc: 'Machinery for preparing, tanning, working of hides, skins or leather', ch: '84' },
  { code: '8454', desc: 'Converters, ladles, ingot moulds for metallurgy', ch: '84' },
  { code: '8455', desc: 'Metal-rolling mills and rolls therefor', ch: '84' },
  { code: '8456', desc: 'Machine-tools operated by laser, ultrasonic, electro-discharge', ch: '84' },
  { code: '8457', desc: 'Machining centres for working metal (CNC machining centres)', ch: '84' },
  { code: '8460', desc: 'Machine-tools for deburring, sharpening, grinding, honing metal', ch: '84' },
  { code: '8461', desc: 'Machine-tools for planing, shaping, slotting, broaching metal', ch: '84' },
  { code: '8462', desc: 'Machine-tools for forging, bending, straightening, pressing metal', ch: '84' },
  { code: '8463', desc: 'Other machine-tools for working metal without removing material', ch: '84' },
  { code: '8464', desc: 'Machine-tools for working stone, ceramics, concrete (diamond cutting)', ch: '84' },
  { code: '8465', desc: 'Machine-tools for working wood, MDF, cork, bone (wood-working CNC)', ch: '84' },
  { code: '8467', desc: 'Tools for working in the hand, pneumatic, hydraulic or with self-contained non-electric motor', ch: '84' },
  { code: '8468', desc: 'Machinery and apparatus for soldering, brazing or welding', ch: '84' },
  { code: '8471', desc: 'Automatic data processing machines (computers, servers)', ch: '84' },
  { code: '847130', desc: 'Portable automatic data processing machines (laptops ≤10 kg)', ch: '84' },
  { code: '847141', desc: 'Other ADP machines comprising a CPU plus input/output unit in same housing', ch: '84' },
  { code: '847149', desc: 'Other ADP machines presented in the form of systems', ch: '84' },
  { code: '847160', desc: 'Input or output units for ADP machines (keyboards, scanners)', ch: '84' },
  { code: '847170', desc: 'Storage units for ADP machines (HDDs, SSDs)', ch: '84' },
  { code: '847180', desc: 'Other ADP units (graphics cards, network cards)', ch: '84' },
  { code: '8473', desc: 'Parts and accessories for machines of heading 8470 to 8472', ch: '84' },
  { code: '8474', desc: 'Machinery for sorting, screening, crushing rock, stone, ores', ch: '84' },
  { code: '8477', desc: 'Machinery for working rubber or plastics (injection moulding)', ch: '84' },
  { code: '8480', desc: 'Moulding boxes for metal foundry; mould bases; casting moulds', ch: '84' },
  { code: '8481', desc: 'Taps, cocks, valves and similar appliances for pipes, tanks', ch: '84' },
  { code: '8482', desc: 'Ball bearings, roller bearings and thrust bearings', ch: '84' },
  { code: '8483', desc: 'Transmission shafts, cranks, bearing housings, gearboxes, pulleys', ch: '84' },
  { code: '8484', desc: 'Gaskets and similar joints of metal sheeting', ch: '84' },
  { code: '8486', desc: 'Machines and apparatus for semiconductor manufacturing', ch: '84' },
  { code: '8487', desc: 'Machinery parts not containing electrical connectors (mechanical seals)', ch: '84' },

  // ── Chapter 85: Electrical machinery ──────────────────────────────────────
  { code: '8501', desc: 'Electric motors and generators (electric motors, alternators)', ch: '85' },
  { code: '850110', desc: 'AC or DC motors of output ≤37.5W', ch: '85' },
  { code: '850120', desc: 'Universal AC/DC motors of output >37.5W', ch: '85' },
  { code: '850131', desc: 'DC motors and generators of output ≤750W', ch: '85' },
  { code: '850132', desc: 'DC motors and generators >750W but ≤75kW', ch: '85' },
  { code: '850151', desc: 'AC motors, single-phase', ch: '85' },
  { code: '850152', desc: 'AC motors, multi-phase of output ≤750W', ch: '85' },
  { code: '850153', desc: 'AC motors, multi-phase >750W but ≤75kW', ch: '85' },
  { code: '850161', desc: 'AC generators (alternators) of output ≤75kVA', ch: '85' },
  { code: '8502', desc: 'Electric generating sets and rotary converters (diesel gensets)', ch: '85' },
  { code: '850211', desc: 'Generating sets with compression-ignition engines ≤75kVA', ch: '85' },
  { code: '850212', desc: 'Generating sets with compression-ignition engines >75kVA but ≤375kVA', ch: '85' },
  { code: '850213', desc: 'Generating sets with compression-ignition engines >375kVA', ch: '85' },
  { code: '8503', desc: 'Parts suitable for use with motors and generators of 8501 or 8502', ch: '85' },
  { code: '8504', desc: 'Electrical transformers, static converters (rectifiers, inverters, UPS)', ch: '85' },
  { code: '850410', desc: 'Ballasts for discharge lamps', ch: '85' },
  { code: '850421', desc: 'Liquid dielectric transformers ≤650kVA', ch: '85' },
  { code: '850422', desc: 'Liquid dielectric transformers >650kVA but ≤10,000kVA', ch: '85' },
  { code: '850423', desc: 'Liquid dielectric transformers >10,000kVA', ch: '85' },
  { code: '850440', desc: 'Static converters (UPS, inverters, rectifiers, battery chargers)', ch: '85' },
  { code: '8506', desc: 'Primary cells and primary batteries (non-rechargeable)', ch: '85' },
  { code: '8507', desc: 'Electric accumulators (rechargeable batteries — Li-ion, lead-acid)', ch: '85' },
  { code: '850710', desc: 'Lead-acid batteries for starting piston engines', ch: '85' },
  { code: '850720', desc: 'Other lead-acid accumulators', ch: '85' },
  { code: '850760', desc: 'Lithium-ion accumulators', ch: '85' },
  { code: '8508', desc: 'Vacuum cleaners', ch: '85' },
  { code: '8509', desc: 'Electro-mechanical household appliances with self-contained electric motor', ch: '85' },
  { code: '8510', desc: 'Shavers, hair clippers, hair-removing appliances with self-contained motor', ch: '85' },
  { code: '8511', desc: 'Electrical ignition or starting equipment for internal combustion engines', ch: '85' },
  { code: '8512', desc: 'Electrical lighting or signalling equipment for vehicles/cycles', ch: '85' },
  { code: '8513', desc: 'Portable electric lamps designed to function by their own source of energy', ch: '85' },
  { code: '8514', desc: 'Industrial or laboratory electric furnaces, ovens and induction heating equipment', ch: '85' },
  { code: '8515', desc: 'Electric (including electrically heated gas) soldering, brazing, welding machines', ch: '85' },
  { code: '8516', desc: 'Electric water heaters, immersion heaters, geysers; electric ovens, toasters', ch: '85' },
  { code: '851610', desc: 'Electric instantaneous or storage water heaters and immersion heaters', ch: '85' },
  { code: '851621', desc: 'Storage heating radiators', ch: '85' },
  { code: '851631', desc: 'Electrothermic hair dryers', ch: '85' },
  { code: '851640', desc: 'Electric smoothing irons', ch: '85' },
  { code: '851650', desc: 'Microwave ovens', ch: '85' },
  { code: '851660', desc: 'Other ovens; cookers, cooking plates, boiling rings, grills and roasters', ch: '85' },
  { code: '851671', desc: 'Coffee or tea makers', ch: '85' },
  { code: '851672', desc: 'Toasters', ch: '85' },
  { code: '851679', desc: 'Other electrothermic appliances (food warmers, induction cooktops)', ch: '85' },
  { code: '8517', desc: 'Telephone sets, smartphones, apparatus for transmission/reception', ch: '85' },
  { code: '851711', desc: 'Line telephone sets with cordless handsets', ch: '85' },
  { code: '851712', desc: 'Mobile phones for cellular networks (smartphones)', ch: '85' },
  { code: '851718', desc: 'Other telephone sets', ch: '85' },
  { code: '851761', desc: 'Base stations (mobile network BTS)', ch: '85' },
  { code: '851762', desc: 'Machines for the reception, conversion and transmission of voice/data/image (routers, switches)', ch: '85' },
  { code: '8518', desc: 'Microphones; loudspeakers; headphones; audio amplifiers; sound equipment', ch: '85' },
  { code: '8519', desc: 'Sound recording or reproducing apparatus (CD/MP3 players)', ch: '85' },
  { code: '8521', desc: 'Video recording or reproducing apparatus (DVRs, Blu-ray)', ch: '85' },
  { code: '8523', desc: 'Discs, tapes, solid-state memory devices for sound/image recording (USB, SSD, memory cards)', ch: '85' },
  { code: '852352', desc: 'Semiconductor media (solid-state non-volatile storage devices — USB flash drives, memory cards)', ch: '85' },
  { code: '8524', desc: 'Flat panel display modules', ch: '85' },
  { code: '8525', desc: 'Transmission apparatus for radio-broadcasting, TV, etc. (CCTV cameras)', ch: '85' },
  { code: '852580', desc: 'Television cameras, digital cameras and video camera recorders', ch: '85' },
  { code: '8526', desc: 'Radar apparatus, radio navigational aid apparatus, GPS', ch: '85' },
  { code: '8527', desc: 'Reception apparatus for radio-broadcasting, car radios', ch: '85' },
  { code: '8528', desc: 'Monitors and projectors; television receivers (TVs)', ch: '85' },
  { code: '852872', desc: 'Other television receivers with flat panel display (LED/LCD/OLED TV)', ch: '85' },
  { code: '8529', desc: 'Parts for apparatus of headings 8525 to 8528 (antenna, display panels)', ch: '85' },
  { code: '8532', desc: 'Electrical capacitors (fixed, variable, adjustable)', ch: '85' },
  { code: '8533', desc: 'Electrical resistors (including rheostats and potentiometers)', ch: '85' },
  { code: '8534', desc: 'Printed circuits (PCBs)', ch: '85' },
  { code: '8535', desc: 'Electrical apparatus for switching/protecting electrical circuits ≥1000V (HT switchgear)', ch: '85' },
  { code: '8536', desc: 'Electrical apparatus for switching/protecting electrical circuits <1000V (MCB, RCCB, contactors)', ch: '85' },
  { code: '853610', desc: 'Fuses (cutouts, fuse links)', ch: '85' },
  { code: '853620', desc: 'Automatic circuit breakers (MCBs, ACBs)', ch: '85' },
  { code: '853630', desc: 'Other apparatus for protecting electrical circuits (RCCB, ELCB)', ch: '85' },
  { code: '853641', desc: 'Relays for voltage ≤60V', ch: '85' },
  { code: '853649', desc: 'Other relays', ch: '85' },
  { code: '853650', desc: 'Other switches (limit switches, push buttons, selector switches)', ch: '85' },
  { code: '853690', desc: 'Other apparatus (plugs, sockets, lamp holders, junction boxes)', ch: '85' },
  { code: '8537', desc: 'Boards, panels, consoles for electric control (switchboards, distribution boards)', ch: '85' },
  { code: '8538', desc: 'Parts for apparatus of headings 8535, 8536 or 8537', ch: '85' },
  { code: '8539', desc: 'Electric filament or discharge lamps; LED lamps', ch: '85' },
  { code: '853931', desc: 'Fluorescent lamps with double-ended cathode (tube lights)', ch: '85' },
  { code: '853940', desc: 'Mercury vapour lamps; sodium vapour lamps; metal halide lamps', ch: '85' },
  { code: '853950', desc: 'LED lamps', ch: '85' },
  { code: '8540', desc: 'Thermionic, cold cathode or photo-cathode valves and tubes', ch: '85' },
  { code: '8541', desc: 'Semiconductor devices — diodes, transistors, solar cells', ch: '85' },
  { code: '854110', desc: 'Diodes other than photosensitive or light emitting diodes', ch: '85' },
  { code: '854121', desc: 'Transistors (other than photosensitive) — dissipation rate <1W', ch: '85' },
  { code: '854140', desc: 'Photosensitive semiconductor devices (solar cells, photodiodes)', ch: '85' },
  { code: '854142', desc: 'Solar cells not assembled in modules or panels', ch: '85' },
  { code: '854143', desc: 'Solar cells assembled in modules or panels', ch: '85' },
  { code: '8542', desc: 'Electronic integrated circuits (ICs, microprocessors, microcontrollers)', ch: '85' },
  { code: '854231', desc: 'Processors and controllers (CPUs, MCUs, DSPs)', ch: '85' },
  { code: '854232', desc: 'Memories (RAM, ROM, Flash)', ch: '85' },
  { code: '854233', desc: 'Amplifiers', ch: '85' },
  { code: '854239', desc: 'Other electronic integrated circuits (ASIC, FPGA)', ch: '85' },
  { code: '8544', desc: 'Insulated wire, cable and other insulated electric conductors (coaxial cable)', ch: '85' },
  { code: '854411', desc: 'Winding wire of copper, insulated', ch: '85' },
  { code: '854419', desc: 'Other winding wire', ch: '85' },
  { code: '854420', desc: 'Co-axial cable and other coaxial electric conductors', ch: '85' },
  { code: '854430', desc: 'Ignition wiring sets and other wiring sets for vehicles', ch: '85' },
  { code: '854442', desc: 'Electric conductors for voltage >80V but ≤1000V, fitted with connectors', ch: '85' },
  { code: '854449', desc: 'Other electric conductors for voltage >80V but ≤1000V', ch: '85' },
  { code: '854460', desc: 'Electric conductors for voltage >1000V', ch: '85' },
  { code: '8545', desc: 'Carbon electrodes, carbon brushes, lamp carbons', ch: '85' },
  { code: '8546', desc: 'Electrical insulators of any material (porcelain, glass, plastic)', ch: '85' },
  { code: '8547', desc: 'Insulating fittings for electrical machines, appliances (conduit tubing)', ch: '85' },
  { code: '8548', desc: 'Waste and scrap of primary cells, primary batteries, electric accumulators', ch: '85' },

  // ── Chapter 87: Vehicles ───────────────────────────────────────────────────
  { code: '8701', desc: 'Tractors (other than tractors of 8709)', ch: '87' },
  { code: '8702', desc: 'Motor vehicles for transport of 10 or more persons (buses)', ch: '87' },
  { code: '8703', desc: 'Motor cars and motor vehicles for transport of persons', ch: '87' },
  { code: '870310', desc: 'Vehicles specially designed for travelling on snow', ch: '87' },
  { code: '870321', desc: 'Cars — spark ignition, engine ≤1000cc (micro/mini cars)', ch: '87' },
  { code: '870322', desc: 'Cars — spark ignition, engine >1000cc but ≤1500cc', ch: '87' },
  { code: '870323', desc: 'Cars — spark ignition, engine >1500cc but ≤3000cc', ch: '87' },
  { code: '870324', desc: 'Cars — spark ignition, engine >3000cc', ch: '87' },
  { code: '870331', desc: 'Cars — compression ignition (diesel), engine ≤1500cc', ch: '87' },
  { code: '870332', desc: 'Cars — compression ignition (diesel), engine >1500cc but ≤2500cc', ch: '87' },
  { code: '870333', desc: 'Cars — compression ignition (diesel), engine >2500cc', ch: '87' },
  { code: '870340', desc: 'Vehicles with both spark ignition and electric motor (hybrid)', ch: '87' },
  { code: '870380', desc: 'Other vehicles with only electric motor (EVs)', ch: '87' },
  { code: '8704', desc: 'Motor vehicles for transport of goods (trucks, lorries, pick-up vans)', ch: '87' },
  { code: '870410', desc: 'Dumpers for off-highway use', ch: '87' },
  { code: '870421', desc: 'Other goods transport vehicles — diesel, GVW ≤5 tonnes', ch: '87' },
  { code: '870422', desc: 'Other goods transport vehicles — diesel, GVW >5 but ≤20 tonnes', ch: '87' },
  { code: '870423', desc: 'Other goods transport vehicles — diesel, GVW >20 tonnes', ch: '87' },
  { code: '8705', desc: 'Special purpose motor vehicles (crane lorries, fire-fighting vehicles, concrete mixers)', ch: '87' },
  { code: '8706', desc: 'Chassis fitted with engines for motor vehicles', ch: '87' },
  { code: '8707', desc: 'Bodies for motor vehicles (including cabs)', ch: '87' },
  { code: '8708', desc: 'Parts and accessories for motor vehicles', ch: '87' },
  { code: '870810', desc: 'Bumpers and parts thereof', ch: '87' },
  { code: '870821', desc: 'Seat belts', ch: '87' },
  { code: '870829', desc: 'Other safety belts and parts of bodies', ch: '87' },
  { code: '870830', desc: 'Brakes and servo-brakes; parts thereof', ch: '87' },
  { code: '870840', desc: 'Gear boxes and parts thereof', ch: '87' },
  { code: '870850', desc: 'Drive axles with differential, whether or not with other transmission components', ch: '87' },
  { code: '870870', desc: 'Road wheels and parts/accessories thereof', ch: '87' },
  { code: '870880', desc: 'Suspension systems and parts thereof (shock absorbers)', ch: '87' },
  { code: '870891', desc: 'Radiators and parts thereof', ch: '87' },
  { code: '870892', desc: 'Silencers and exhaust pipes; parts thereof', ch: '87' },
  { code: '870894', desc: 'Steering wheels, steering columns and steering boxes', ch: '87' },
  { code: '870895', desc: 'Safety airbags with inflator system; parts thereof', ch: '87' },
  { code: '870899', desc: 'Other parts and accessories for motor vehicles (NOS)', ch: '87' },
  { code: '8711', desc: 'Motorcycles and cycles fitted with an auxiliary motor (mopeds)', ch: '87' },
  { code: '871110', desc: 'Motorcycles with reciprocating spark ignition engine ≤50cc', ch: '87' },
  { code: '871120', desc: 'Motorcycles with engine >50cc but ≤250cc', ch: '87' },
  { code: '871130', desc: 'Motorcycles with engine >250cc but ≤500cc', ch: '87' },
  { code: '871140', desc: 'Motorcycles with engine >500cc but ≤800cc', ch: '87' },
  { code: '871150', desc: 'Motorcycles with engine >800cc', ch: '87' },
  { code: '871160', desc: 'Motorcycles with electric motor', ch: '87' },
  { code: '8712', desc: 'Bicycles and other cycles (including delivery tricycles), not motorised', ch: '87' },
  { code: '8713', desc: 'Invalid carriages, whether or not motorised', ch: '87' },
  { code: '8714', desc: 'Parts and accessories for vehicles of headings 8711 to 8713', ch: '87' },
  { code: '8715', desc: 'Baby carriages and parts thereof', ch: '87' },
  { code: '8716', desc: 'Trailers and semi-trailers; other vehicles not mechanically propelled', ch: '87' },

  // ── Chapter 88: Aircraft ──────────────────────────────────────────────────
  { code: '8801', desc: 'Balloons and dirigibles; gliders, hang gliders, other non-powered aircraft', ch: '88' },
  { code: '8802', desc: 'Other aircraft (helicopters, aeroplanes, drones)', ch: '88' },
  { code: '880211', desc: 'Helicopters of unladen weight ≤2,000 kg', ch: '88' },
  { code: '880212', desc: 'Helicopters of unladen weight >2,000 kg', ch: '88' },
  { code: '880220', desc: 'Aeroplanes and aircraft for civil aviation — unladen weight ≤2,000 kg', ch: '88' },
  { code: '880230', desc: 'Aeroplanes and aircraft — unladen weight >2,000 kg but ≤15,000 kg', ch: '88' },
  { code: '880240', desc: 'Aeroplanes and aircraft — unladen weight >15,000 kg', ch: '88' },
  { code: '880260', desc: 'Unmanned aircraft (UAVs, commercial drones)', ch: '88' },

  // ── Chapter 90: Optical/Medical instruments ────────────────────────────────
  { code: '9001', desc: 'Optical fibres and optical fibre bundles; optical fibre cables', ch: '90' },
  { code: '9002', desc: 'Lenses, prisms, mirrors and other optical elements (camera lenses)', ch: '90' },
  { code: '9003', desc: 'Frames and mountings for spectacles, goggles or the like', ch: '90' },
  { code: '9004', desc: 'Spectacles, goggles and the like (corrective, protective, other)', ch: '90' },
  { code: '9005', desc: 'Binoculars, monoculars, telescopes, astronomical instruments', ch: '90' },
  { code: '9006', desc: 'Photographic (other than cinematographic) cameras', ch: '90' },
  { code: '9008', desc: 'Image projectors; photographic enlargers and reducers', ch: '90' },
  { code: '9011', desc: 'Optical microscopes', ch: '90' },
  { code: '9013', desc: 'Liquid crystal devices; lasers; other optical appliances and instruments', ch: '90' },
  { code: '9014', desc: 'Direction finding compasses; navigational instruments (GPS excluded)', ch: '90' },
  { code: '9015', desc: 'Surveying, hydrographic, oceanographic instruments (theodolites, levels)', ch: '90' },
  { code: '9017', desc: 'Drawing, marking-out or mathematical calculating instruments (drafting instruments)', ch: '90' },
  { code: '9018', desc: 'Instruments and appliances used in medical, surgical, dental, veterinary sciences', ch: '90' },
  { code: '901810', desc: 'Electro-diagnostic apparatus (ECG, EEG, MRI, CT scan)', ch: '90' },
  { code: '901813', desc: 'Magnetic resonance imaging apparatus (MRI machines)', ch: '90' },
  { code: '901819', desc: 'Other electro-diagnostic apparatus', ch: '90' },
  { code: '901820', desc: 'Ultraviolet or infrared ray apparatus (UV therapy, physiotherapy)', ch: '90' },
  { code: '901831', desc: 'Syringes, with or without needles', ch: '90' },
  { code: '901832', desc: 'Tubular metal needles and needles for sutures', ch: '90' },
  { code: '901839', desc: 'Other needles, catheters, cannulae', ch: '90' },
  { code: '901841', desc: 'Dental drill engines', ch: '90' },
  { code: '901849', desc: 'Other instruments used in dental sciences', ch: '90' },
  { code: '901850', desc: 'Ophthalmic instruments and appliances (slit lamps, tonometers)', ch: '90' },
  { code: '901890', desc: 'Other medical instruments (stethoscopes, blood pressure monitors)', ch: '90' },
  { code: '9019', desc: 'Mechano-therapy appliances; massage apparatus; oxygen therapy apparatus (ventilators)', ch: '90' },
  { code: '9020', desc: 'Other breathing appliances and gas masks (CPAP machines)', ch: '90' },
  { code: '9021', desc: 'Orthopaedic appliances; splints; artificial body parts; hearing aids; pacemakers', ch: '90' },
  { code: '902110', desc: 'Orthopaedic or fracture appliances', ch: '90' },
  { code: '902131', desc: 'Artificial joints (hip, knee replacements)', ch: '90' },
  { code: '902139', desc: 'Other artificial parts of the body (stents, implants)', ch: '90' },
  { code: '902140', desc: 'Hearing aids (excluding parts/accessories)', ch: '90' },
  { code: '902150', desc: 'Pacemakers for stimulating heart muscles', ch: '90' },
  { code: '9022', desc: 'Apparatus based on X-ray or alpha, beta or gamma radiations (X-ray machines)', ch: '90' },
  { code: '902211', desc: 'Tomography apparatus (CT scanners)', ch: '90' },
  { code: '902212', desc: 'Other apparatus for medical, surgical, dental or veterinary use (X-ray)', ch: '90' },
  { code: '9025', desc: 'Hydrometers; thermometers, pyrometers, barometers, hygrometers', ch: '90' },
  { code: '9026', desc: 'Instruments for measuring flow, level, pressure of liquids or gases (flow meters)', ch: '90' },
  { code: '9027', desc: 'Instruments and apparatus for physical or chemical analysis (spectrometers, chromatographs)', ch: '90' },
  { code: '9029', desc: 'Revolution counters, production counters, taximeters, pedometers', ch: '90' },
  { code: '9030', desc: 'Oscilloscopes, spectrum analysers; electrical measurement instruments (multimeters)', ch: '90' },
  { code: '9031', desc: 'Measuring or checking instruments not specified elsewhere (CMM machines)', ch: '90' },
  { code: '9032', desc: 'Automatic regulating or controlling instruments and apparatus (thermostats, PIDs)', ch: '90' },

  // ── Chapter 94: Furniture ──────────────────────────────────────────────────
  { code: '9401', desc: 'Seats (other than 9402), whether or not convertible into beds (chairs, sofas)', ch: '94' },
  { code: '9402', desc: 'Medical, surgical, dental or veterinary furniture (operating tables, beds)', ch: '94' },
  { code: '9403', desc: 'Other furniture and parts thereof (tables, desks, cabinets, wardrobes)', ch: '94' },
  { code: '940310', desc: 'Metal furniture of a kind used in offices', ch: '94' },
  { code: '940320', desc: 'Other metal furniture (racks, shelving)', ch: '94' },
  { code: '940330', desc: 'Wooden furniture of a kind used in offices', ch: '94' },
  { code: '940340', desc: 'Wooden furniture of a kind used in the kitchen', ch: '94' },
  { code: '940350', desc: 'Wooden furniture of a kind used in the bedroom (beds, wardrobes)', ch: '94' },
  { code: '940360', desc: 'Other wooden furniture', ch: '94' },
  { code: '940380', desc: 'Furniture of other materials including cane, osier, bamboo, plastics', ch: '94' },
  { code: '9404', desc: 'Mattress supports; mattresses; sleeping bags; bedding (pillows, quilts)', ch: '94' },
  { code: '9405', desc: 'Lamps and lighting fittings (LED lights, ceiling fans with lights)', ch: '94' },
  { code: '940540', desc: 'Electric lamps and lighting fittings (LED bulkheads, downlights)', ch: '94' },
  { code: '940560', desc: 'Illuminated signs, illuminated nameplates and the like', ch: '94' },
  { code: '9406', desc: 'Prefabricated buildings (porta-cabins, modular buildings)', ch: '94' },

  // ── Chapter 95: Toys and sports ────────────────────────────────────────────
  { code: '9503', desc: 'Tricycles, scooters, pedal cars and similar wheeled toys; dolls\' carriages; dolls', ch: '95' },
  { code: '9504', desc: 'Video game consoles and machines; playing cards; billiard tables', ch: '95' },
  { code: '9505', desc: 'Festive, carnival or other entertainment articles (Christmas decorations)', ch: '95' },
  { code: '9506', desc: 'Articles and equipment for sports (cricket, football, gym equipment)', ch: '95' },
  { code: '950611', desc: 'Ski skates (snow skis) and ski-fastenings', ch: '95' },
  { code: '950620', desc: 'Water-skis, surf-boards, sailboards and other water-sport equipment', ch: '95' },
  { code: '950640', desc: 'Articles and equipment for table-tennis', ch: '95' },
  { code: '950651', desc: 'Lawn-tennis rackets', ch: '95' },
  { code: '950659', desc: 'Other rackets', ch: '95' },
  { code: '950661', desc: 'Lawn-tennis balls', ch: '95' },
  { code: '950662', desc: 'Inflatable balls (football, volleyball, basketball)', ch: '95' },
  { code: '950669', desc: 'Other balls (cricket balls, golf balls)', ch: '95' },
  { code: '950691', desc: 'Articles and equipment for general physical exercise (gym weights, treadmills)', ch: '95' },
  { code: '9507', desc: 'Fishing rods, fish-hooks and other fishing tackle', ch: '95' },
  { code: '9508', desc: 'Roundabouts, swings, shooting galleries and other fairground amusements', ch: '95' },

  // ── Chapter 96: Miscellaneous ──────────────────────────────────────────────
  { code: '9601', desc: 'Worked ivory, bone, tortoiseshell; articles thereof', ch: '96' },
  { code: '9602', desc: 'Worked vegetable or mineral carving material; articles thereof', ch: '96' },
  { code: '9603', desc: 'Brooms, brushes (toothbrushes, shaving brushes, paint brushes)', ch: '96' },
  { code: '9604', desc: 'Hand sieves and hand riddles', ch: '96' },
  { code: '9605', desc: 'Travel sets for personal toilet, sewing or shoe/clothes cleaning', ch: '96' },
  { code: '9606', desc: 'Buttons, press-fasteners, snap-fasteners and press-studs; button moulds', ch: '96' },
  { code: '9607', desc: 'Slide fasteners (zip fasteners) and parts thereof', ch: '96' },
  { code: '9608', desc: 'Ball point pens; felt tipped and other porous-tipped pens; fountain pens', ch: '96' },
  { code: '9609', desc: 'Pencils, crayons, pencil leads, pastels, drawing charcoals', ch: '96' },
  { code: '9610', desc: 'Slates and boards, with writing or drawing surfaces', ch: '96' },
  { code: '9612', desc: 'Typewriter or similar ribbons; ink-pads (printer cartridges, ribbons)', ch: '96' },
  { code: '9613', desc: 'Cigarette lighters and other lighters (gas, mechanical, electrical)', ch: '96' },
  { code: '9614', desc: 'Smoking pipes (including pipe bowls) and cigar or cigarette holders', ch: '96' },
  { code: '9615', desc: 'Combs, hair-slides and the like; hairpins, curling pins', ch: '96' },
  { code: '9616', desc: 'Scent sprays and similar toilet sprays; powder puffs and pads', ch: '96' },
  { code: '9617', desc: 'Vacuum flasks and other vacuum vessels', ch: '96' },
  { code: '9618', desc: 'Tailors\' dummies and other lay figures; automata and other animated displays', ch: '96' },
  { code: '9619', desc: 'Sanitary towels, tampons, napkins for babies, adult diapers', ch: '96' },
];
